# Generated by cxbind. Do not edit.
from collections.abc import Callable
from typing import Any, ClassVar

class _pybind11_type(type): ...  # stand-in for pybind11's metaclass

class EventType(metaclass=_pybind11_type):
    FIRST: ClassVar[EventType]
    QUIT: ClassVar[EventType]
    TERMINATING: ClassVar[EventType]
    LOW_MEMORY: ClassVar[EventType]
    WILL_ENTER_BACKGROUND: ClassVar[EventType]
    DID_ENTER_BACKGROUND: ClassVar[EventType]
    WILL_ENTER_FOREGROUND: ClassVar[EventType]
    DID_ENTER_FOREGROUND: ClassVar[EventType]
    LOCALE_CHANGED: ClassVar[EventType]
    SYSTEM_THEME_CHANGED: ClassVar[EventType]
    DISPLAY_ORIENTATION: ClassVar[EventType]
    DISPLAY_ADDED: ClassVar[EventType]
    DISPLAY_REMOVED: ClassVar[EventType]
    DISPLAY_MOVED: ClassVar[EventType]
    DISPLAY_DESKTOP_MODE_CHANGED: ClassVar[EventType]
    DISPLAY_CURRENT_MODE_CHANGED: ClassVar[EventType]
    DISPLAY_CONTENT_SCALE_CHANGED: ClassVar[EventType]
    DISPLAY_USABLE_BOUNDS_CHANGED: ClassVar[EventType]
    DISPLAY_FIRST: ClassVar[EventType]
    DISPLAY_LAST: ClassVar[EventType]
    WINDOW_SHOWN: ClassVar[EventType]
    WINDOW_HIDDEN: ClassVar[EventType]
    WINDOW_EXPOSED: ClassVar[EventType]
    WINDOW_MOVED: ClassVar[EventType]
    WINDOW_RESIZED: ClassVar[EventType]
    WINDOW_PIXEL_SIZE_CHANGED: ClassVar[EventType]
    WINDOW_METAL_VIEW_RESIZED: ClassVar[EventType]
    WINDOW_MINIMIZED: ClassVar[EventType]
    WINDOW_MAXIMIZED: ClassVar[EventType]
    WINDOW_RESTORED: ClassVar[EventType]
    WINDOW_MOUSE_ENTER: ClassVar[EventType]
    WINDOW_MOUSE_LEAVE: ClassVar[EventType]
    WINDOW_FOCUS_GAINED: ClassVar[EventType]
    WINDOW_FOCUS_LOST: ClassVar[EventType]
    WINDOW_CLOSE_REQUESTED: ClassVar[EventType]
    WINDOW_HIT_TEST: ClassVar[EventType]
    WINDOW_ICCPROF_CHANGED: ClassVar[EventType]
    WINDOW_DISPLAY_CHANGED: ClassVar[EventType]
    WINDOW_DISPLAY_SCALE_CHANGED: ClassVar[EventType]
    WINDOW_SAFE_AREA_CHANGED: ClassVar[EventType]
    WINDOW_OCCLUDED: ClassVar[EventType]
    WINDOW_ENTER_FULLSCREEN: ClassVar[EventType]
    WINDOW_LEAVE_FULLSCREEN: ClassVar[EventType]
    WINDOW_DESTROYED: ClassVar[EventType]
    WINDOW_HDR_STATE_CHANGED: ClassVar[EventType]
    WINDOW_SETTINGS_CHANGED: ClassVar[EventType]
    WINDOW_FIRST: ClassVar[EventType]
    WINDOW_LAST: ClassVar[EventType]
    KEY_DOWN: ClassVar[EventType]
    KEY_UP: ClassVar[EventType]
    TEXT_EDITING: ClassVar[EventType]
    TEXT_INPUT: ClassVar[EventType]
    KEYMAP_CHANGED: ClassVar[EventType]
    KEYBOARD_ADDED: ClassVar[EventType]
    KEYBOARD_REMOVED: ClassVar[EventType]
    TEXT_EDITING_CANDIDATES: ClassVar[EventType]
    SCREEN_KEYBOARD_SHOWN: ClassVar[EventType]
    SCREEN_KEYBOARD_HIDDEN: ClassVar[EventType]
    KEYBOARD_FIRST: ClassVar[EventType]
    KEYBOARD_LAST: ClassVar[EventType]
    MOUSE_MOTION: ClassVar[EventType]
    MOUSE_BUTTON_DOWN: ClassVar[EventType]
    MOUSE_BUTTON_UP: ClassVar[EventType]
    MOUSE_WHEEL: ClassVar[EventType]
    MOUSE_ADDED: ClassVar[EventType]
    MOUSE_REMOVED: ClassVar[EventType]
    MOUSE_FIRST: ClassVar[EventType]
    MOUSE_LAST: ClassVar[EventType]
    JOYSTICK_AXIS_MOTION: ClassVar[EventType]
    JOYSTICK_BALL_MOTION: ClassVar[EventType]
    JOYSTICK_HAT_MOTION: ClassVar[EventType]
    JOYSTICK_BUTTON_DOWN: ClassVar[EventType]
    JOYSTICK_BUTTON_UP: ClassVar[EventType]
    JOYSTICK_ADDED: ClassVar[EventType]
    JOYSTICK_REMOVED: ClassVar[EventType]
    JOYSTICK_BATTERY_UPDATED: ClassVar[EventType]
    JOYSTICK_UPDATE_COMPLETE: ClassVar[EventType]
    JOYSTICK_FIRST: ClassVar[EventType]
    JOYSTICK_LAST: ClassVar[EventType]
    GAMEPAD_AXIS_MOTION: ClassVar[EventType]
    GAMEPAD_BUTTON_DOWN: ClassVar[EventType]
    GAMEPAD_BUTTON_UP: ClassVar[EventType]
    GAMEPAD_ADDED: ClassVar[EventType]
    GAMEPAD_REMOVED: ClassVar[EventType]
    GAMEPAD_REMAPPED: ClassVar[EventType]
    GAMEPAD_TOUCHPAD_DOWN: ClassVar[EventType]
    GAMEPAD_TOUCHPAD_MOTION: ClassVar[EventType]
    GAMEPAD_TOUCHPAD_UP: ClassVar[EventType]
    GAMEPAD_SENSOR_UPDATE: ClassVar[EventType]
    GAMEPAD_UPDATE_COMPLETE: ClassVar[EventType]
    GAMEPAD_STEAM_HANDLE_UPDATED: ClassVar[EventType]
    GAMEPAD_CAPSENSE_TOUCH: ClassVar[EventType]
    GAMEPAD_CAPSENSE_RELEASE: ClassVar[EventType]
    GAMEPAD_FIRST: ClassVar[EventType]
    GAMEPAD_LAST: ClassVar[EventType]
    FINGER_DOWN: ClassVar[EventType]
    FINGER_UP: ClassVar[EventType]
    FINGER_MOTION: ClassVar[EventType]
    FINGER_CANCELED: ClassVar[EventType]
    FINGER_FIRST: ClassVar[EventType]
    FINGER_LAST: ClassVar[EventType]
    PINCH_BEGIN: ClassVar[EventType]
    PINCH_UPDATE: ClassVar[EventType]
    PINCH_END: ClassVar[EventType]
    PINCH_FIRST: ClassVar[EventType]
    PINCH_LAST: ClassVar[EventType]
    CLIPBOARD_UPDATE: ClassVar[EventType]
    CLIPBOARD_FIRST: ClassVar[EventType]
    CLIPBOARD_LAST: ClassVar[EventType]
    DROP_FILE: ClassVar[EventType]
    DROP_TEXT: ClassVar[EventType]
    DROP_BEGIN: ClassVar[EventType]
    DROP_COMPLETE: ClassVar[EventType]
    DROP_POSITION: ClassVar[EventType]
    DROP_FIRST: ClassVar[EventType]
    DROP_LAST: ClassVar[EventType]
    AUDIO_DEVICE_ADDED: ClassVar[EventType]
    AUDIO_DEVICE_REMOVED: ClassVar[EventType]
    AUDIO_DEVICE_FORMAT_CHANGED: ClassVar[EventType]
    AUDIO_DEVICE_FIRST: ClassVar[EventType]
    AUDIO_DEVICE_LAST: ClassVar[EventType]
    SENSOR_UPDATE: ClassVar[EventType]
    SENSOR_FIRST: ClassVar[EventType]
    SENSOR_LAST: ClassVar[EventType]
    PEN_PROXIMITY_IN: ClassVar[EventType]
    PEN_PROXIMITY_OUT: ClassVar[EventType]
    PEN_DOWN: ClassVar[EventType]
    PEN_UP: ClassVar[EventType]
    PEN_BUTTON_DOWN: ClassVar[EventType]
    PEN_BUTTON_UP: ClassVar[EventType]
    PEN_MOTION: ClassVar[EventType]
    PEN_AXIS: ClassVar[EventType]
    PEN_FIRST: ClassVar[EventType]
    PEN_LAST: ClassVar[EventType]
    CAMERA_DEVICE_ADDED: ClassVar[EventType]
    CAMERA_DEVICE_REMOVED: ClassVar[EventType]
    CAMERA_DEVICE_APPROVED: ClassVar[EventType]
    CAMERA_DEVICE_DENIED: ClassVar[EventType]
    CAMERA_DEVICE_FIRST: ClassVar[EventType]
    CAMERA_DEVICE_LAST: ClassVar[EventType]
    NOTIFICATION_ACTION_INVOKED: ClassVar[EventType]
    NOTIFICATION_FIRST: ClassVar[EventType]
    NOTIFICATION_LAST: ClassVar[EventType]
    RENDER_TARGETS_RESET: ClassVar[EventType]
    RENDER_DEVICE_RESET: ClassVar[EventType]
    RENDER_DEVICE_LOST: ClassVar[EventType]
    RENDER_FIRST: ClassVar[EventType]
    RENDER_LAST: ClassVar[EventType]
    PRIVATE0: ClassVar[EventType]
    PRIVATE1: ClassVar[EventType]
    PRIVATE2: ClassVar[EventType]
    PRIVATE3: ClassVar[EventType]
    POLL_SENTINEL: ClassVar[EventType]
    USER: ClassVar[EventType]
    LAST: ClassVar[EventType]
    ENUM_PADDING: ClassVar[EventType]
    __members__: ClassVar[dict[str, EventType]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class CommonEvent(metaclass=_pybind11_type):
    type: int
    reserved: int
    timestamp: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DisplayEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    display_id: int
    data1: int
    data2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class WindowEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    data1: int
    data2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class KeyboardDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class KeyboardEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    scancode: Any
    key: int
    mod: int
    raw: int
    down: bool
    repeat: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TextEditingEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    text: str
    start: int
    length: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TextEditingCandidatesEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    num_candidates: int
    selected_candidate: int
    horizontal: bool
    padding1: int
    padding2: int
    padding3: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TextInputEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    text: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MouseDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MouseMotionEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    state: int
    x: float
    y: float
    xrel: float
    yrel: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MouseButtonEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    button: int
    down: bool
    clicks: int
    padding: int
    x: float
    y: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MouseWheelEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    x: float
    y: float
    direction: Any
    mouse_x: float
    mouse_y: float
    integer_x: int
    integer_y: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyAxisEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    axis: int
    padding1: int
    padding2: int
    padding3: int
    value: int
    padding4: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyBallEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    ball: int
    padding1: int
    padding2: int
    padding3: int
    xrel: int
    yrel: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyHatEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    hat: int
    value: int
    padding1: int
    padding2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyButtonEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    button: int
    down: bool
    padding1: int
    padding2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class JoyBatteryEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    state: Any
    percent: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadAxisEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    axis: int
    padding1: int
    padding2: int
    padding3: int
    value: int
    padding4: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadButtonEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    button: int
    down: bool
    padding1: int
    padding2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadTouchpadEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    touchpad: int
    finger: int
    x: float
    y: float
    pressure: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadSensorEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    sensor: int
    @property
    def data(self) -> list[float]: ...
    sensor_timestamp: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class GamepadCapSenseEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    capsense: int
    down: bool
    padding1: int
    padding2: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class AudioDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    recording: bool
    padding1: int
    padding2: int
    padding3: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CameraDeviceEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class NotificationEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    action_id: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class RenderEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TouchFingerEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    touch_id: int
    finger_id: int
    x: float
    y: float
    dx: float
    dy: float
    pressure: float
    window_id: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PinchFingerEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    scale: float
    window_id: int
    span_x: float
    span_y: float
    focus_x: float
    focus_y: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PenProximityEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    pen_state: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PenMotionEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    pen_state: int
    x: float
    y: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PenTouchEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    pen_state: int
    x: float
    y: float
    eraser: bool
    down: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PenButtonEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    pen_state: int
    x: float
    y: float
    button: int
    down: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PenAxisEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    which: int
    pen_state: int
    x: float
    y: float
    axis: Any
    value: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DropEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    window_id: int
    x: float
    y: float
    source: str
    data: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ClipboardEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    owner: bool
    num_mime_types: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SensorEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    which: int
    @property
    def data(self) -> list[float]: ...
    sensor_timestamp: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QuitEvent(metaclass=_pybind11_type):
    type: EventType
    reserved: int
    timestamp: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class UserEvent(metaclass=_pybind11_type):
    type: int
    reserved: int
    timestamp: int
    window_id: int
    code: int
    data1: Any
    data2: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def pump_events() -> None: ...
class EventAction(metaclass=_pybind11_type):
    ADDEVENT: ClassVar[EventAction]
    PEEKEVENT: ClassVar[EventAction]
    GETEVENT: ClassVar[EventAction]
    __members__: ClassVar[dict[str, EventAction]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def peep_events(events: Any, numevents: int, action: EventAction, min_type: int, max_type: int) -> int: ...
def has_event(type: int) -> bool: ...
def has_events(min_type: int, max_type: int) -> bool: ...
def flush_event(type: int) -> None: ...
def flush_events(min_type: int, max_type: int) -> None: ...
def wait_event(event: Any) -> bool: ...
def wait_event_timeout(event: Any, timeout_ms: int) -> bool: ...
def push_event(event: Any) -> bool: ...
def set_event_filter(filter: Callable[[Any, Any], bool], userdata: Any) -> None: ...
def add_event_watch(filter: Callable[[Any, Any], bool], userdata: Any) -> bool: ...
def remove_event_watch(filter: Callable[[Any, Any], bool], userdata: Any) -> None: ...
def filter_events(filter: Callable[[Any, Any], bool], userdata: Any) -> None: ...
def set_event_enabled(type: int, enabled: bool) -> None: ...
def event_enabled(type: int) -> bool: ...
def register_events(numevents: int) -> int: ...
def get_event_description(event: Any, buf: str, buflen: int) -> int: ...
FIRST: EventType
QUIT: EventType
TERMINATING: EventType
LOW_MEMORY: EventType
WILL_ENTER_BACKGROUND: EventType
DID_ENTER_BACKGROUND: EventType
WILL_ENTER_FOREGROUND: EventType
DID_ENTER_FOREGROUND: EventType
LOCALE_CHANGED: EventType
SYSTEM_THEME_CHANGED: EventType
DISPLAY_ORIENTATION: EventType
DISPLAY_ADDED: EventType
DISPLAY_REMOVED: EventType
DISPLAY_MOVED: EventType
DISPLAY_DESKTOP_MODE_CHANGED: EventType
DISPLAY_CURRENT_MODE_CHANGED: EventType
DISPLAY_CONTENT_SCALE_CHANGED: EventType
DISPLAY_USABLE_BOUNDS_CHANGED: EventType
DISPLAY_FIRST: EventType
DISPLAY_LAST: EventType
WINDOW_SHOWN: EventType
WINDOW_HIDDEN: EventType
WINDOW_EXPOSED: EventType
WINDOW_MOVED: EventType
WINDOW_RESIZED: EventType
WINDOW_PIXEL_SIZE_CHANGED: EventType
WINDOW_METAL_VIEW_RESIZED: EventType
WINDOW_MINIMIZED: EventType
WINDOW_MAXIMIZED: EventType
WINDOW_RESTORED: EventType
WINDOW_MOUSE_ENTER: EventType
WINDOW_MOUSE_LEAVE: EventType
WINDOW_FOCUS_GAINED: EventType
WINDOW_FOCUS_LOST: EventType
WINDOW_CLOSE_REQUESTED: EventType
WINDOW_HIT_TEST: EventType
WINDOW_ICCPROF_CHANGED: EventType
WINDOW_DISPLAY_CHANGED: EventType
WINDOW_DISPLAY_SCALE_CHANGED: EventType
WINDOW_SAFE_AREA_CHANGED: EventType
WINDOW_OCCLUDED: EventType
WINDOW_ENTER_FULLSCREEN: EventType
WINDOW_LEAVE_FULLSCREEN: EventType
WINDOW_DESTROYED: EventType
WINDOW_HDR_STATE_CHANGED: EventType
WINDOW_SETTINGS_CHANGED: EventType
WINDOW_FIRST: EventType
WINDOW_LAST: EventType
KEY_DOWN: EventType
KEY_UP: EventType
TEXT_EDITING: EventType
TEXT_INPUT: EventType
KEYMAP_CHANGED: EventType
KEYBOARD_ADDED: EventType
KEYBOARD_REMOVED: EventType
TEXT_EDITING_CANDIDATES: EventType
SCREEN_KEYBOARD_SHOWN: EventType
SCREEN_KEYBOARD_HIDDEN: EventType
KEYBOARD_FIRST: EventType
KEYBOARD_LAST: EventType
MOUSE_MOTION: EventType
MOUSE_BUTTON_DOWN: EventType
MOUSE_BUTTON_UP: EventType
MOUSE_WHEEL: EventType
MOUSE_ADDED: EventType
MOUSE_REMOVED: EventType
MOUSE_FIRST: EventType
MOUSE_LAST: EventType
JOYSTICK_AXIS_MOTION: EventType
JOYSTICK_BALL_MOTION: EventType
JOYSTICK_HAT_MOTION: EventType
JOYSTICK_BUTTON_DOWN: EventType
JOYSTICK_BUTTON_UP: EventType
JOYSTICK_ADDED: EventType
JOYSTICK_REMOVED: EventType
JOYSTICK_BATTERY_UPDATED: EventType
JOYSTICK_UPDATE_COMPLETE: EventType
JOYSTICK_FIRST: EventType
JOYSTICK_LAST: EventType
GAMEPAD_AXIS_MOTION: EventType
GAMEPAD_BUTTON_DOWN: EventType
GAMEPAD_BUTTON_UP: EventType
GAMEPAD_ADDED: EventType
GAMEPAD_REMOVED: EventType
GAMEPAD_REMAPPED: EventType
GAMEPAD_TOUCHPAD_DOWN: EventType
GAMEPAD_TOUCHPAD_MOTION: EventType
GAMEPAD_TOUCHPAD_UP: EventType
GAMEPAD_SENSOR_UPDATE: EventType
GAMEPAD_UPDATE_COMPLETE: EventType
GAMEPAD_STEAM_HANDLE_UPDATED: EventType
GAMEPAD_CAPSENSE_TOUCH: EventType
GAMEPAD_CAPSENSE_RELEASE: EventType
GAMEPAD_FIRST: EventType
GAMEPAD_LAST: EventType
FINGER_DOWN: EventType
FINGER_UP: EventType
FINGER_MOTION: EventType
FINGER_CANCELED: EventType
FINGER_FIRST: EventType
FINGER_LAST: EventType
PINCH_BEGIN: EventType
PINCH_UPDATE: EventType
PINCH_END: EventType
PINCH_FIRST: EventType
PINCH_LAST: EventType
CLIPBOARD_UPDATE: EventType
CLIPBOARD_FIRST: EventType
CLIPBOARD_LAST: EventType
DROP_FILE: EventType
DROP_TEXT: EventType
DROP_BEGIN: EventType
DROP_COMPLETE: EventType
DROP_POSITION: EventType
DROP_FIRST: EventType
DROP_LAST: EventType
AUDIO_DEVICE_ADDED: EventType
AUDIO_DEVICE_REMOVED: EventType
AUDIO_DEVICE_FORMAT_CHANGED: EventType
AUDIO_DEVICE_FIRST: EventType
AUDIO_DEVICE_LAST: EventType
SENSOR_UPDATE: EventType
SENSOR_FIRST: EventType
SENSOR_LAST: EventType
PEN_PROXIMITY_IN: EventType
PEN_PROXIMITY_OUT: EventType
PEN_DOWN: EventType
PEN_UP: EventType
PEN_BUTTON_DOWN: EventType
PEN_BUTTON_UP: EventType
PEN_MOTION: EventType
PEN_AXIS: EventType
PEN_FIRST: EventType
PEN_LAST: EventType
CAMERA_DEVICE_ADDED: EventType
CAMERA_DEVICE_REMOVED: EventType
CAMERA_DEVICE_APPROVED: EventType
CAMERA_DEVICE_DENIED: EventType
CAMERA_DEVICE_FIRST: EventType
CAMERA_DEVICE_LAST: EventType
NOTIFICATION_ACTION_INVOKED: EventType
NOTIFICATION_FIRST: EventType
NOTIFICATION_LAST: EventType
RENDER_TARGETS_RESET: EventType
RENDER_DEVICE_RESET: EventType
RENDER_DEVICE_LOST: EventType
RENDER_FIRST: EventType
RENDER_LAST: EventType
PRIVATE0: EventType
PRIVATE1: EventType
PRIVATE2: EventType
PRIVATE3: EventType
POLL_SENTINEL: EventType
USER: EventType
LAST: EventType
ENUM_PADDING: EventType
ADDEVENT: EventAction
PEEKEVENT: EventAction
GETEVENT: EventAction

class AppResult(metaclass=_pybind11_type):
    APP_CONTINUE: ClassVar[AppResult]
    APP_SUCCESS: ClassVar[AppResult]
    APP_FAILURE: ClassVar[AppResult]
    __members__: ClassVar[dict[str, AppResult]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def init(flags: int) -> bool: ...
def init_sub_system(flags: int) -> bool: ...
def quit_sub_system(flags: int) -> None: ...
def was_init(flags: int) -> int: ...
def quit() -> None: ...
def is_main_thread() -> bool: ...
def run_on_main_thread(callback: Callable[[Any], None], userdata: Any, wait_complete: bool) -> bool: ...
def set_app_metadata(appname: str, appversion: str, appidentifier: str) -> bool: ...
def set_app_metadata_property(name: str, value: str) -> bool: ...
def get_app_metadata_property(name: str) -> str: ...
APP_CONTINUE: AppResult
APP_SUCCESS: AppResult
APP_FAILURE: AppResult

def has_keyboard() -> bool: ...
def get_keyboards(count: int) -> tuple[int, int]: ...
def get_keyboard_name_for_id(instance_id: int) -> str: ...
def get_keyboard_focus() -> Any: ...
def get_keyboard_state(numkeys: int) -> tuple[bool, int]: ...
def reset_keyboard() -> None: ...
def get_mod_state() -> int: ...
def set_mod_state(modstate: int) -> None: ...
def get_key_from_scancode(scancode: Any, modstate: int, key_event: bool) -> int: ...
def get_scancode_from_key(key: int, modstate: int) -> tuple[Any, int]: ...
def set_scancode_name(scancode: Any, name: str) -> bool: ...
def get_scancode_name(scancode: Any) -> str: ...
def get_scancode_from_name(name: str) -> Any: ...
def get_key_name(key: int) -> str: ...
def get_key_from_name(name: str) -> int: ...
def start_text_input(window: Any) -> bool: ...
class TextInputType(metaclass=_pybind11_type):
    TEXTINPUT_TYPE_TEXT: ClassVar[TextInputType]
    TEXTINPUT_TYPE_TEXT_NAME: ClassVar[TextInputType]
    TEXTINPUT_TYPE_TEXT_EMAIL: ClassVar[TextInputType]
    TEXTINPUT_TYPE_TEXT_USERNAME: ClassVar[TextInputType]
    TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN: ClassVar[TextInputType]
    TEXTINPUT_TYPE_TEXT_PASSWORD_VISIBLE: ClassVar[TextInputType]
    TEXTINPUT_TYPE_NUMBER: ClassVar[TextInputType]
    TEXTINPUT_TYPE_NUMBER_PASSWORD_HIDDEN: ClassVar[TextInputType]
    TEXTINPUT_TYPE_NUMBER_PASSWORD_VISIBLE: ClassVar[TextInputType]
    __members__: ClassVar[dict[str, TextInputType]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class Capitalization(metaclass=_pybind11_type):
    CAPITALIZE_NONE: ClassVar[Capitalization]
    CAPITALIZE_SENTENCES: ClassVar[Capitalization]
    CAPITALIZE_WORDS: ClassVar[Capitalization]
    CAPITALIZE_LETTERS: ClassVar[Capitalization]
    __members__: ClassVar[dict[str, Capitalization]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def start_text_input_with_properties(window: Any, props: int) -> bool: ...
def text_input_active(window: Any) -> bool: ...
def stop_text_input(window: Any) -> bool: ...
def clear_composition(window: Any) -> bool: ...
def set_text_input_area(window: Any, rect: Any, cursor: int) -> bool: ...
def get_text_input_area(window: Any, rect: Any, cursor: int) -> tuple[bool, int]: ...
def has_screen_keyboard_support() -> bool: ...
def screen_keyboard_shown(window: Any) -> bool: ...
TEXTINPUT_TYPE_TEXT: TextInputType
TEXTINPUT_TYPE_TEXT_NAME: TextInputType
TEXTINPUT_TYPE_TEXT_EMAIL: TextInputType
TEXTINPUT_TYPE_TEXT_USERNAME: TextInputType
TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN: TextInputType
TEXTINPUT_TYPE_TEXT_PASSWORD_VISIBLE: TextInputType
TEXTINPUT_TYPE_NUMBER: TextInputType
TEXTINPUT_TYPE_NUMBER_PASSWORD_HIDDEN: TextInputType
TEXTINPUT_TYPE_NUMBER_PASSWORD_VISIBLE: TextInputType
CAPITALIZE_NONE: Capitalization
CAPITALIZE_SENTENCES: Capitalization
CAPITALIZE_WORDS: Capitalization
CAPITALIZE_LETTERS: Capitalization

class SystemCursor(metaclass=_pybind11_type):
    SYSTEM_CURSOR_DEFAULT: ClassVar[SystemCursor]
    SYSTEM_CURSOR_TEXT: ClassVar[SystemCursor]
    SYSTEM_CURSOR_WAIT: ClassVar[SystemCursor]
    SYSTEM_CURSOR_CROSSHAIR: ClassVar[SystemCursor]
    SYSTEM_CURSOR_PROGRESS: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NWSE_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NESW_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_EW_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NS_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_MOVE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NOT_ALLOWED: ClassVar[SystemCursor]
    SYSTEM_CURSOR_POINTER: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NW_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_N_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NE_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_E_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_SE_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_S_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_SW_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_W_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_CONTEXT_MENU: ClassVar[SystemCursor]
    SYSTEM_CURSOR_HELP: ClassVar[SystemCursor]
    SYSTEM_CURSOR_CELL: ClassVar[SystemCursor]
    SYSTEM_CURSOR_VERTICAL_TEXT: ClassVar[SystemCursor]
    SYSTEM_CURSOR_ALIAS: ClassVar[SystemCursor]
    SYSTEM_CURSOR_COPY: ClassVar[SystemCursor]
    SYSTEM_CURSOR_NO_DROP: ClassVar[SystemCursor]
    SYSTEM_CURSOR_GRAB: ClassVar[SystemCursor]
    SYSTEM_CURSOR_GRABBING: ClassVar[SystemCursor]
    SYSTEM_CURSOR_COL_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_ROW_RESIZE: ClassVar[SystemCursor]
    SYSTEM_CURSOR_ALL_SCROLL: ClassVar[SystemCursor]
    SYSTEM_CURSOR_ZOOM_IN: ClassVar[SystemCursor]
    SYSTEM_CURSOR_ZOOM_OUT: ClassVar[SystemCursor]
    SYSTEM_CURSOR_COUNT: ClassVar[SystemCursor]
    __members__: ClassVar[dict[str, SystemCursor]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class MouseWheelDirection(metaclass=_pybind11_type):
    MOUSEWHEEL_NORMAL: ClassVar[MouseWheelDirection]
    MOUSEWHEEL_FLIPPED: ClassVar[MouseWheelDirection]
    __members__: ClassVar[dict[str, MouseWheelDirection]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class CursorFrameInfo(metaclass=_pybind11_type):
    surface: Any
    duration: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def has_mouse() -> bool: ...
def get_mice(count: int) -> tuple[int, int]: ...
def get_mouse_name_for_id(instance_id: int) -> str: ...
def get_mouse_focus() -> Any: ...
def get_mouse_state(x: float, y: float) -> tuple[int, float, float]: ...
def get_global_mouse_state(x: float, y: float) -> tuple[int, float, float]: ...
def get_relative_mouse_state(x: float, y: float) -> tuple[int, float, float]: ...
def warp_mouse_in_window(window: Any, x: float, y: float) -> None: ...
def warp_mouse_global(x: float, y: float) -> bool: ...
def set_relative_mouse_transform(callback: Callable[[Any, int, Any, int, float, float], None], userdata: Any) -> bool: ...
def set_window_relative_mouse_mode(window: Any, enabled: bool) -> bool: ...
def get_window_relative_mouse_mode(window: Any) -> bool: ...
def capture_mouse(enabled: bool) -> bool: ...
def create_cursor(data: int, mask: int, w: int, h: int, hot_x: int, hot_y: int) -> Any: ...
def create_color_cursor(surface: Any, hot_x: int, hot_y: int) -> Any: ...
def create_animated_cursor(frames: CursorFrameInfo, frame_count: int, hot_x: int, hot_y: int) -> Any: ...
def create_system_cursor(id: SystemCursor) -> Any: ...
def set_cursor(cursor: Any) -> bool: ...
def get_cursor() -> Any: ...
def get_default_cursor() -> Any: ...
def destroy_cursor(cursor: Any) -> None: ...
def show_cursor() -> bool: ...
def hide_cursor() -> bool: ...
def cursor_visible() -> bool: ...
SYSTEM_CURSOR_DEFAULT: SystemCursor
SYSTEM_CURSOR_TEXT: SystemCursor
SYSTEM_CURSOR_WAIT: SystemCursor
SYSTEM_CURSOR_CROSSHAIR: SystemCursor
SYSTEM_CURSOR_PROGRESS: SystemCursor
SYSTEM_CURSOR_NWSE_RESIZE: SystemCursor
SYSTEM_CURSOR_NESW_RESIZE: SystemCursor
SYSTEM_CURSOR_EW_RESIZE: SystemCursor
SYSTEM_CURSOR_NS_RESIZE: SystemCursor
SYSTEM_CURSOR_MOVE: SystemCursor
SYSTEM_CURSOR_NOT_ALLOWED: SystemCursor
SYSTEM_CURSOR_POINTER: SystemCursor
SYSTEM_CURSOR_NW_RESIZE: SystemCursor
SYSTEM_CURSOR_N_RESIZE: SystemCursor
SYSTEM_CURSOR_NE_RESIZE: SystemCursor
SYSTEM_CURSOR_E_RESIZE: SystemCursor
SYSTEM_CURSOR_SE_RESIZE: SystemCursor
SYSTEM_CURSOR_S_RESIZE: SystemCursor
SYSTEM_CURSOR_SW_RESIZE: SystemCursor
SYSTEM_CURSOR_W_RESIZE: SystemCursor
SYSTEM_CURSOR_CONTEXT_MENU: SystemCursor
SYSTEM_CURSOR_HELP: SystemCursor
SYSTEM_CURSOR_CELL: SystemCursor
SYSTEM_CURSOR_VERTICAL_TEXT: SystemCursor
SYSTEM_CURSOR_ALIAS: SystemCursor
SYSTEM_CURSOR_COPY: SystemCursor
SYSTEM_CURSOR_NO_DROP: SystemCursor
SYSTEM_CURSOR_GRAB: SystemCursor
SYSTEM_CURSOR_GRABBING: SystemCursor
SYSTEM_CURSOR_COL_RESIZE: SystemCursor
SYSTEM_CURSOR_ROW_RESIZE: SystemCursor
SYSTEM_CURSOR_ALL_SCROLL: SystemCursor
SYSTEM_CURSOR_ZOOM_IN: SystemCursor
SYSTEM_CURSOR_ZOOM_OUT: SystemCursor
SYSTEM_CURSOR_COUNT: SystemCursor
MOUSEWHEEL_NORMAL: MouseWheelDirection
MOUSEWHEEL_FLIPPED: MouseWheelDirection

class PropertyType(metaclass=_pybind11_type):
    INVALID: ClassVar[PropertyType]
    POINTER: ClassVar[PropertyType]
    STRING: ClassVar[PropertyType]
    NUMBER: ClassVar[PropertyType]
    FLOAT: ClassVar[PropertyType]
    BOOLEAN: ClassVar[PropertyType]
    __members__: ClassVar[dict[str, PropertyType]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def get_global_properties() -> int: ...
def create_properties() -> int: ...
def copy_properties(src: int, dst: int) -> bool: ...
def lock_properties(props: int) -> bool: ...
def unlock_properties(props: int) -> None: ...
def set_pointer_property_with_cleanup(props: int, name: str, value: Any, cleanup: Callable[[Any, Any], None], userdata: Any) -> bool: ...
def set_pointer_property(props: int, name: str, value: Any) -> bool: ...
def set_string_property(props: int, name: str, value: str) -> bool: ...
def set_number_property(props: int, name: str, value: int) -> bool: ...
def set_float_property(props: int, name: str, value: float) -> bool: ...
def set_boolean_property(props: int, name: str, value: bool) -> bool: ...
def has_property(props: int, name: str) -> bool: ...
def get_property_type(props: int, name: str) -> PropertyType: ...
def get_pointer_property(props: int, name: str, default_value: Any) -> Any: ...
def get_string_property(props: int, name: str, default_value: str) -> str: ...
def get_number_property(props: int, name: str, default_value: int) -> int: ...
def get_float_property(props: int, name: str, default_value: float) -> float: ...
def get_boolean_property(props: int, name: str, default_value: bool) -> bool: ...
def clear_property(props: int, name: str) -> bool: ...
def get_num_properties(props: int) -> int: ...
def enumerate_properties(props: int, callback: Callable[[Any, int, str], None], userdata: Any) -> bool: ...
def destroy_properties(props: int) -> None: ...
INVALID: PropertyType
POINTER: PropertyType
STRING: PropertyType
NUMBER: PropertyType
FLOAT: PropertyType
BOOLEAN: PropertyType

class Scancode(metaclass=_pybind11_type):
    SCANCODE_UNKNOWN: ClassVar[Scancode]
    SCANCODE_A: ClassVar[Scancode]
    SCANCODE_B: ClassVar[Scancode]
    SCANCODE_C: ClassVar[Scancode]
    SCANCODE_D: ClassVar[Scancode]
    SCANCODE_E: ClassVar[Scancode]
    SCANCODE_F: ClassVar[Scancode]
    SCANCODE_G: ClassVar[Scancode]
    SCANCODE_H: ClassVar[Scancode]
    SCANCODE_I: ClassVar[Scancode]
    SCANCODE_J: ClassVar[Scancode]
    SCANCODE_K: ClassVar[Scancode]
    SCANCODE_L: ClassVar[Scancode]
    SCANCODE_M: ClassVar[Scancode]
    SCANCODE_N: ClassVar[Scancode]
    SCANCODE_O: ClassVar[Scancode]
    SCANCODE_P: ClassVar[Scancode]
    SCANCODE_Q: ClassVar[Scancode]
    SCANCODE_R: ClassVar[Scancode]
    SCANCODE_S: ClassVar[Scancode]
    SCANCODE_T: ClassVar[Scancode]
    SCANCODE_U: ClassVar[Scancode]
    SCANCODE_V: ClassVar[Scancode]
    SCANCODE_W: ClassVar[Scancode]
    SCANCODE_X: ClassVar[Scancode]
    SCANCODE_Y: ClassVar[Scancode]
    SCANCODE_Z: ClassVar[Scancode]
    SCANCODE_1: ClassVar[Scancode]
    SCANCODE_2: ClassVar[Scancode]
    SCANCODE_3: ClassVar[Scancode]
    SCANCODE_4: ClassVar[Scancode]
    SCANCODE_5: ClassVar[Scancode]
    SCANCODE_6: ClassVar[Scancode]
    SCANCODE_7: ClassVar[Scancode]
    SCANCODE_8: ClassVar[Scancode]
    SCANCODE_9: ClassVar[Scancode]
    SCANCODE_0: ClassVar[Scancode]
    SCANCODE_RETURN: ClassVar[Scancode]
    SCANCODE_ESCAPE: ClassVar[Scancode]
    SCANCODE_BACKSPACE: ClassVar[Scancode]
    SCANCODE_TAB: ClassVar[Scancode]
    SCANCODE_SPACE: ClassVar[Scancode]
    SCANCODE_MINUS: ClassVar[Scancode]
    SCANCODE_EQUALS: ClassVar[Scancode]
    SCANCODE_LEFTBRACKET: ClassVar[Scancode]
    SCANCODE_RIGHTBRACKET: ClassVar[Scancode]
    SCANCODE_BACKSLASH: ClassVar[Scancode]
    SCANCODE_NONUSHASH: ClassVar[Scancode]
    SCANCODE_SEMICOLON: ClassVar[Scancode]
    SCANCODE_APOSTROPHE: ClassVar[Scancode]
    SCANCODE_GRAVE: ClassVar[Scancode]
    SCANCODE_COMMA: ClassVar[Scancode]
    SCANCODE_PERIOD: ClassVar[Scancode]
    SCANCODE_SLASH: ClassVar[Scancode]
    SCANCODE_CAPSLOCK: ClassVar[Scancode]
    SCANCODE_F1: ClassVar[Scancode]
    SCANCODE_F2: ClassVar[Scancode]
    SCANCODE_F3: ClassVar[Scancode]
    SCANCODE_F4: ClassVar[Scancode]
    SCANCODE_F5: ClassVar[Scancode]
    SCANCODE_F6: ClassVar[Scancode]
    SCANCODE_F7: ClassVar[Scancode]
    SCANCODE_F8: ClassVar[Scancode]
    SCANCODE_F9: ClassVar[Scancode]
    SCANCODE_F10: ClassVar[Scancode]
    SCANCODE_F11: ClassVar[Scancode]
    SCANCODE_F12: ClassVar[Scancode]
    SCANCODE_PRINTSCREEN: ClassVar[Scancode]
    SCANCODE_SCROLLLOCK: ClassVar[Scancode]
    SCANCODE_PAUSE: ClassVar[Scancode]
    SCANCODE_INSERT: ClassVar[Scancode]
    SCANCODE_HOME: ClassVar[Scancode]
    SCANCODE_PAGEUP: ClassVar[Scancode]
    SCANCODE_DELETE: ClassVar[Scancode]
    SCANCODE_END: ClassVar[Scancode]
    SCANCODE_PAGEDOWN: ClassVar[Scancode]
    SCANCODE_RIGHT: ClassVar[Scancode]
    SCANCODE_LEFT: ClassVar[Scancode]
    SCANCODE_DOWN: ClassVar[Scancode]
    SCANCODE_UP: ClassVar[Scancode]
    SCANCODE_NUMLOCKCLEAR: ClassVar[Scancode]
    SCANCODE_KP_DIVIDE: ClassVar[Scancode]
    SCANCODE_KP_MULTIPLY: ClassVar[Scancode]
    SCANCODE_KP_MINUS: ClassVar[Scancode]
    SCANCODE_KP_PLUS: ClassVar[Scancode]
    SCANCODE_KP_ENTER: ClassVar[Scancode]
    SCANCODE_KP_1: ClassVar[Scancode]
    SCANCODE_KP_2: ClassVar[Scancode]
    SCANCODE_KP_3: ClassVar[Scancode]
    SCANCODE_KP_4: ClassVar[Scancode]
    SCANCODE_KP_5: ClassVar[Scancode]
    SCANCODE_KP_6: ClassVar[Scancode]
    SCANCODE_KP_7: ClassVar[Scancode]
    SCANCODE_KP_8: ClassVar[Scancode]
    SCANCODE_KP_9: ClassVar[Scancode]
    SCANCODE_KP_0: ClassVar[Scancode]
    SCANCODE_KP_PERIOD: ClassVar[Scancode]
    SCANCODE_NONUSBACKSLASH: ClassVar[Scancode]
    SCANCODE_APPLICATION: ClassVar[Scancode]
    SCANCODE_POWER: ClassVar[Scancode]
    SCANCODE_KP_EQUALS: ClassVar[Scancode]
    SCANCODE_F13: ClassVar[Scancode]
    SCANCODE_F14: ClassVar[Scancode]
    SCANCODE_F15: ClassVar[Scancode]
    SCANCODE_F16: ClassVar[Scancode]
    SCANCODE_F17: ClassVar[Scancode]
    SCANCODE_F18: ClassVar[Scancode]
    SCANCODE_F19: ClassVar[Scancode]
    SCANCODE_F20: ClassVar[Scancode]
    SCANCODE_F21: ClassVar[Scancode]
    SCANCODE_F22: ClassVar[Scancode]
    SCANCODE_F23: ClassVar[Scancode]
    SCANCODE_F24: ClassVar[Scancode]
    SCANCODE_EXECUTE: ClassVar[Scancode]
    SCANCODE_HELP: ClassVar[Scancode]
    SCANCODE_MENU: ClassVar[Scancode]
    SCANCODE_SELECT: ClassVar[Scancode]
    SCANCODE_STOP: ClassVar[Scancode]
    SCANCODE_AGAIN: ClassVar[Scancode]
    SCANCODE_UNDO: ClassVar[Scancode]
    SCANCODE_CUT: ClassVar[Scancode]
    SCANCODE_COPY: ClassVar[Scancode]
    SCANCODE_PASTE: ClassVar[Scancode]
    SCANCODE_FIND: ClassVar[Scancode]
    SCANCODE_MUTE: ClassVar[Scancode]
    SCANCODE_VOLUMEUP: ClassVar[Scancode]
    SCANCODE_VOLUMEDOWN: ClassVar[Scancode]
    SCANCODE_KP_COMMA: ClassVar[Scancode]
    SCANCODE_KP_EQUALSAS400: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL1: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL2: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL3: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL4: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL5: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL6: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL7: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL8: ClassVar[Scancode]
    SCANCODE_INTERNATIONAL9: ClassVar[Scancode]
    SCANCODE_LANG1: ClassVar[Scancode]
    SCANCODE_LANG2: ClassVar[Scancode]
    SCANCODE_LANG3: ClassVar[Scancode]
    SCANCODE_LANG4: ClassVar[Scancode]
    SCANCODE_LANG5: ClassVar[Scancode]
    SCANCODE_LANG6: ClassVar[Scancode]
    SCANCODE_LANG7: ClassVar[Scancode]
    SCANCODE_LANG8: ClassVar[Scancode]
    SCANCODE_LANG9: ClassVar[Scancode]
    SCANCODE_ALTERASE: ClassVar[Scancode]
    SCANCODE_SYSREQ: ClassVar[Scancode]
    SCANCODE_CANCEL: ClassVar[Scancode]
    SCANCODE_CLEAR: ClassVar[Scancode]
    SCANCODE_PRIOR: ClassVar[Scancode]
    SCANCODE_RETURN2: ClassVar[Scancode]
    SCANCODE_SEPARATOR: ClassVar[Scancode]
    SCANCODE_OUT: ClassVar[Scancode]
    SCANCODE_OPER: ClassVar[Scancode]
    SCANCODE_CLEARAGAIN: ClassVar[Scancode]
    SCANCODE_CRSEL: ClassVar[Scancode]
    SCANCODE_EXSEL: ClassVar[Scancode]
    SCANCODE_FRONT: ClassVar[Scancode]
    SCANCODE_KP_00: ClassVar[Scancode]
    SCANCODE_KP_000: ClassVar[Scancode]
    SCANCODE_THOUSANDSSEPARATOR: ClassVar[Scancode]
    SCANCODE_DECIMALSEPARATOR: ClassVar[Scancode]
    SCANCODE_CURRENCYUNIT: ClassVar[Scancode]
    SCANCODE_CURRENCYSUBUNIT: ClassVar[Scancode]
    SCANCODE_KP_LEFTPAREN: ClassVar[Scancode]
    SCANCODE_KP_RIGHTPAREN: ClassVar[Scancode]
    SCANCODE_KP_LEFTBRACE: ClassVar[Scancode]
    SCANCODE_KP_RIGHTBRACE: ClassVar[Scancode]
    SCANCODE_KP_TAB: ClassVar[Scancode]
    SCANCODE_KP_BACKSPACE: ClassVar[Scancode]
    SCANCODE_KP_A: ClassVar[Scancode]
    SCANCODE_KP_B: ClassVar[Scancode]
    SCANCODE_KP_C: ClassVar[Scancode]
    SCANCODE_KP_D: ClassVar[Scancode]
    SCANCODE_KP_E: ClassVar[Scancode]
    SCANCODE_KP_F: ClassVar[Scancode]
    SCANCODE_KP_XOR: ClassVar[Scancode]
    SCANCODE_KP_POWER: ClassVar[Scancode]
    SCANCODE_KP_PERCENT: ClassVar[Scancode]
    SCANCODE_KP_LESS: ClassVar[Scancode]
    SCANCODE_KP_GREATER: ClassVar[Scancode]
    SCANCODE_KP_AMPERSAND: ClassVar[Scancode]
    SCANCODE_KP_DBLAMPERSAND: ClassVar[Scancode]
    SCANCODE_KP_VERTICALBAR: ClassVar[Scancode]
    SCANCODE_KP_DBLVERTICALBAR: ClassVar[Scancode]
    SCANCODE_KP_COLON: ClassVar[Scancode]
    SCANCODE_KP_HASH: ClassVar[Scancode]
    SCANCODE_KP_SPACE: ClassVar[Scancode]
    SCANCODE_KP_AT: ClassVar[Scancode]
    SCANCODE_KP_EXCLAM: ClassVar[Scancode]
    SCANCODE_KP_MEMSTORE: ClassVar[Scancode]
    SCANCODE_KP_MEMRECALL: ClassVar[Scancode]
    SCANCODE_KP_MEMCLEAR: ClassVar[Scancode]
    SCANCODE_KP_MEMADD: ClassVar[Scancode]
    SCANCODE_KP_MEMSUBTRACT: ClassVar[Scancode]
    SCANCODE_KP_MEMMULTIPLY: ClassVar[Scancode]
    SCANCODE_KP_MEMDIVIDE: ClassVar[Scancode]
    SCANCODE_KP_PLUSMINUS: ClassVar[Scancode]
    SCANCODE_KP_CLEAR: ClassVar[Scancode]
    SCANCODE_KP_CLEARENTRY: ClassVar[Scancode]
    SCANCODE_KP_BINARY: ClassVar[Scancode]
    SCANCODE_KP_OCTAL: ClassVar[Scancode]
    SCANCODE_KP_DECIMAL: ClassVar[Scancode]
    SCANCODE_KP_HEXADECIMAL: ClassVar[Scancode]
    SCANCODE_LCTRL: ClassVar[Scancode]
    SCANCODE_LSHIFT: ClassVar[Scancode]
    SCANCODE_LALT: ClassVar[Scancode]
    SCANCODE_LGUI: ClassVar[Scancode]
    SCANCODE_RCTRL: ClassVar[Scancode]
    SCANCODE_RSHIFT: ClassVar[Scancode]
    SCANCODE_RALT: ClassVar[Scancode]
    SCANCODE_RGUI: ClassVar[Scancode]
    SCANCODE_MODE: ClassVar[Scancode]
    SCANCODE_SLEEP: ClassVar[Scancode]
    SCANCODE_WAKE: ClassVar[Scancode]
    SCANCODE_CHANNEL_INCREMENT: ClassVar[Scancode]
    SCANCODE_CHANNEL_DECREMENT: ClassVar[Scancode]
    SCANCODE_MEDIA_PLAY: ClassVar[Scancode]
    SCANCODE_MEDIA_PAUSE: ClassVar[Scancode]
    SCANCODE_MEDIA_RECORD: ClassVar[Scancode]
    SCANCODE_MEDIA_FAST_FORWARD: ClassVar[Scancode]
    SCANCODE_MEDIA_REWIND: ClassVar[Scancode]
    SCANCODE_MEDIA_NEXT_TRACK: ClassVar[Scancode]
    SCANCODE_MEDIA_PREVIOUS_TRACK: ClassVar[Scancode]
    SCANCODE_MEDIA_STOP: ClassVar[Scancode]
    SCANCODE_MEDIA_EJECT: ClassVar[Scancode]
    SCANCODE_MEDIA_PLAY_PAUSE: ClassVar[Scancode]
    SCANCODE_MEDIA_SELECT: ClassVar[Scancode]
    SCANCODE_AC_NEW: ClassVar[Scancode]
    SCANCODE_AC_OPEN: ClassVar[Scancode]
    SCANCODE_AC_CLOSE: ClassVar[Scancode]
    SCANCODE_AC_EXIT: ClassVar[Scancode]
    SCANCODE_AC_SAVE: ClassVar[Scancode]
    SCANCODE_AC_PRINT: ClassVar[Scancode]
    SCANCODE_AC_PROPERTIES: ClassVar[Scancode]
    SCANCODE_AC_SEARCH: ClassVar[Scancode]
    SCANCODE_AC_HOME: ClassVar[Scancode]
    SCANCODE_AC_BACK: ClassVar[Scancode]
    SCANCODE_AC_FORWARD: ClassVar[Scancode]
    SCANCODE_AC_STOP: ClassVar[Scancode]
    SCANCODE_AC_REFRESH: ClassVar[Scancode]
    SCANCODE_AC_BOOKMARKS: ClassVar[Scancode]
    SCANCODE_SOFTLEFT: ClassVar[Scancode]
    SCANCODE_SOFTRIGHT: ClassVar[Scancode]
    SCANCODE_CALL: ClassVar[Scancode]
    SCANCODE_ENDCALL: ClassVar[Scancode]
    SCANCODE_RESERVED: ClassVar[Scancode]
    SCANCODE_COUNT: ClassVar[Scancode]
    __members__: ClassVar[dict[str, Scancode]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

SCANCODE_UNKNOWN: Scancode
SCANCODE_A: Scancode
SCANCODE_B: Scancode
SCANCODE_C: Scancode
SCANCODE_D: Scancode
SCANCODE_E: Scancode
SCANCODE_F: Scancode
SCANCODE_G: Scancode
SCANCODE_H: Scancode
SCANCODE_I: Scancode
SCANCODE_J: Scancode
SCANCODE_K: Scancode
SCANCODE_L: Scancode
SCANCODE_M: Scancode
SCANCODE_N: Scancode
SCANCODE_O: Scancode
SCANCODE_P: Scancode
SCANCODE_Q: Scancode
SCANCODE_R: Scancode
SCANCODE_S: Scancode
SCANCODE_T: Scancode
SCANCODE_U: Scancode
SCANCODE_V: Scancode
SCANCODE_W: Scancode
SCANCODE_X: Scancode
SCANCODE_Y: Scancode
SCANCODE_Z: Scancode
SCANCODE_1: Scancode
SCANCODE_2: Scancode
SCANCODE_3: Scancode
SCANCODE_4: Scancode
SCANCODE_5: Scancode
SCANCODE_6: Scancode
SCANCODE_7: Scancode
SCANCODE_8: Scancode
SCANCODE_9: Scancode
SCANCODE_0: Scancode
SCANCODE_RETURN: Scancode
SCANCODE_ESCAPE: Scancode
SCANCODE_BACKSPACE: Scancode
SCANCODE_TAB: Scancode
SCANCODE_SPACE: Scancode
SCANCODE_MINUS: Scancode
SCANCODE_EQUALS: Scancode
SCANCODE_LEFTBRACKET: Scancode
SCANCODE_RIGHTBRACKET: Scancode
SCANCODE_BACKSLASH: Scancode
SCANCODE_NONUSHASH: Scancode
SCANCODE_SEMICOLON: Scancode
SCANCODE_APOSTROPHE: Scancode
SCANCODE_GRAVE: Scancode
SCANCODE_COMMA: Scancode
SCANCODE_PERIOD: Scancode
SCANCODE_SLASH: Scancode
SCANCODE_CAPSLOCK: Scancode
SCANCODE_F1: Scancode
SCANCODE_F2: Scancode
SCANCODE_F3: Scancode
SCANCODE_F4: Scancode
SCANCODE_F5: Scancode
SCANCODE_F6: Scancode
SCANCODE_F7: Scancode
SCANCODE_F8: Scancode
SCANCODE_F9: Scancode
SCANCODE_F10: Scancode
SCANCODE_F11: Scancode
SCANCODE_F12: Scancode
SCANCODE_PRINTSCREEN: Scancode
SCANCODE_SCROLLLOCK: Scancode
SCANCODE_PAUSE: Scancode
SCANCODE_INSERT: Scancode
SCANCODE_HOME: Scancode
SCANCODE_PAGEUP: Scancode
SCANCODE_DELETE: Scancode
SCANCODE_END: Scancode
SCANCODE_PAGEDOWN: Scancode
SCANCODE_RIGHT: Scancode
SCANCODE_LEFT: Scancode
SCANCODE_DOWN: Scancode
SCANCODE_UP: Scancode
SCANCODE_NUMLOCKCLEAR: Scancode
SCANCODE_KP_DIVIDE: Scancode
SCANCODE_KP_MULTIPLY: Scancode
SCANCODE_KP_MINUS: Scancode
SCANCODE_KP_PLUS: Scancode
SCANCODE_KP_ENTER: Scancode
SCANCODE_KP_1: Scancode
SCANCODE_KP_2: Scancode
SCANCODE_KP_3: Scancode
SCANCODE_KP_4: Scancode
SCANCODE_KP_5: Scancode
SCANCODE_KP_6: Scancode
SCANCODE_KP_7: Scancode
SCANCODE_KP_8: Scancode
SCANCODE_KP_9: Scancode
SCANCODE_KP_0: Scancode
SCANCODE_KP_PERIOD: Scancode
SCANCODE_NONUSBACKSLASH: Scancode
SCANCODE_APPLICATION: Scancode
SCANCODE_POWER: Scancode
SCANCODE_KP_EQUALS: Scancode
SCANCODE_F13: Scancode
SCANCODE_F14: Scancode
SCANCODE_F15: Scancode
SCANCODE_F16: Scancode
SCANCODE_F17: Scancode
SCANCODE_F18: Scancode
SCANCODE_F19: Scancode
SCANCODE_F20: Scancode
SCANCODE_F21: Scancode
SCANCODE_F22: Scancode
SCANCODE_F23: Scancode
SCANCODE_F24: Scancode
SCANCODE_EXECUTE: Scancode
SCANCODE_HELP: Scancode
SCANCODE_MENU: Scancode
SCANCODE_SELECT: Scancode
SCANCODE_STOP: Scancode
SCANCODE_AGAIN: Scancode
SCANCODE_UNDO: Scancode
SCANCODE_CUT: Scancode
SCANCODE_COPY: Scancode
SCANCODE_PASTE: Scancode
SCANCODE_FIND: Scancode
SCANCODE_MUTE: Scancode
SCANCODE_VOLUMEUP: Scancode
SCANCODE_VOLUMEDOWN: Scancode
SCANCODE_KP_COMMA: Scancode
SCANCODE_KP_EQUALSAS400: Scancode
SCANCODE_INTERNATIONAL1: Scancode
SCANCODE_INTERNATIONAL2: Scancode
SCANCODE_INTERNATIONAL3: Scancode
SCANCODE_INTERNATIONAL4: Scancode
SCANCODE_INTERNATIONAL5: Scancode
SCANCODE_INTERNATIONAL6: Scancode
SCANCODE_INTERNATIONAL7: Scancode
SCANCODE_INTERNATIONAL8: Scancode
SCANCODE_INTERNATIONAL9: Scancode
SCANCODE_LANG1: Scancode
SCANCODE_LANG2: Scancode
SCANCODE_LANG3: Scancode
SCANCODE_LANG4: Scancode
SCANCODE_LANG5: Scancode
SCANCODE_LANG6: Scancode
SCANCODE_LANG7: Scancode
SCANCODE_LANG8: Scancode
SCANCODE_LANG9: Scancode
SCANCODE_ALTERASE: Scancode
SCANCODE_SYSREQ: Scancode
SCANCODE_CANCEL: Scancode
SCANCODE_CLEAR: Scancode
SCANCODE_PRIOR: Scancode
SCANCODE_RETURN2: Scancode
SCANCODE_SEPARATOR: Scancode
SCANCODE_OUT: Scancode
SCANCODE_OPER: Scancode
SCANCODE_CLEARAGAIN: Scancode
SCANCODE_CRSEL: Scancode
SCANCODE_EXSEL: Scancode
SCANCODE_FRONT: Scancode
SCANCODE_KP_00: Scancode
SCANCODE_KP_000: Scancode
SCANCODE_THOUSANDSSEPARATOR: Scancode
SCANCODE_DECIMALSEPARATOR: Scancode
SCANCODE_CURRENCYUNIT: Scancode
SCANCODE_CURRENCYSUBUNIT: Scancode
SCANCODE_KP_LEFTPAREN: Scancode
SCANCODE_KP_RIGHTPAREN: Scancode
SCANCODE_KP_LEFTBRACE: Scancode
SCANCODE_KP_RIGHTBRACE: Scancode
SCANCODE_KP_TAB: Scancode
SCANCODE_KP_BACKSPACE: Scancode
SCANCODE_KP_A: Scancode
SCANCODE_KP_B: Scancode
SCANCODE_KP_C: Scancode
SCANCODE_KP_D: Scancode
SCANCODE_KP_E: Scancode
SCANCODE_KP_F: Scancode
SCANCODE_KP_XOR: Scancode
SCANCODE_KP_POWER: Scancode
SCANCODE_KP_PERCENT: Scancode
SCANCODE_KP_LESS: Scancode
SCANCODE_KP_GREATER: Scancode
SCANCODE_KP_AMPERSAND: Scancode
SCANCODE_KP_DBLAMPERSAND: Scancode
SCANCODE_KP_VERTICALBAR: Scancode
SCANCODE_KP_DBLVERTICALBAR: Scancode
SCANCODE_KP_COLON: Scancode
SCANCODE_KP_HASH: Scancode
SCANCODE_KP_SPACE: Scancode
SCANCODE_KP_AT: Scancode
SCANCODE_KP_EXCLAM: Scancode
SCANCODE_KP_MEMSTORE: Scancode
SCANCODE_KP_MEMRECALL: Scancode
SCANCODE_KP_MEMCLEAR: Scancode
SCANCODE_KP_MEMADD: Scancode
SCANCODE_KP_MEMSUBTRACT: Scancode
SCANCODE_KP_MEMMULTIPLY: Scancode
SCANCODE_KP_MEMDIVIDE: Scancode
SCANCODE_KP_PLUSMINUS: Scancode
SCANCODE_KP_CLEAR: Scancode
SCANCODE_KP_CLEARENTRY: Scancode
SCANCODE_KP_BINARY: Scancode
SCANCODE_KP_OCTAL: Scancode
SCANCODE_KP_DECIMAL: Scancode
SCANCODE_KP_HEXADECIMAL: Scancode
SCANCODE_LCTRL: Scancode
SCANCODE_LSHIFT: Scancode
SCANCODE_LALT: Scancode
SCANCODE_LGUI: Scancode
SCANCODE_RCTRL: Scancode
SCANCODE_RSHIFT: Scancode
SCANCODE_RALT: Scancode
SCANCODE_RGUI: Scancode
SCANCODE_MODE: Scancode
SCANCODE_SLEEP: Scancode
SCANCODE_WAKE: Scancode
SCANCODE_CHANNEL_INCREMENT: Scancode
SCANCODE_CHANNEL_DECREMENT: Scancode
SCANCODE_MEDIA_PLAY: Scancode
SCANCODE_MEDIA_PAUSE: Scancode
SCANCODE_MEDIA_RECORD: Scancode
SCANCODE_MEDIA_FAST_FORWARD: Scancode
SCANCODE_MEDIA_REWIND: Scancode
SCANCODE_MEDIA_NEXT_TRACK: Scancode
SCANCODE_MEDIA_PREVIOUS_TRACK: Scancode
SCANCODE_MEDIA_STOP: Scancode
SCANCODE_MEDIA_EJECT: Scancode
SCANCODE_MEDIA_PLAY_PAUSE: Scancode
SCANCODE_MEDIA_SELECT: Scancode
SCANCODE_AC_NEW: Scancode
SCANCODE_AC_OPEN: Scancode
SCANCODE_AC_CLOSE: Scancode
SCANCODE_AC_EXIT: Scancode
SCANCODE_AC_SAVE: Scancode
SCANCODE_AC_PRINT: Scancode
SCANCODE_AC_PROPERTIES: Scancode
SCANCODE_AC_SEARCH: Scancode
SCANCODE_AC_HOME: Scancode
SCANCODE_AC_BACK: Scancode
SCANCODE_AC_FORWARD: Scancode
SCANCODE_AC_STOP: Scancode
SCANCODE_AC_REFRESH: Scancode
SCANCODE_AC_BOOKMARKS: Scancode
SCANCODE_SOFTLEFT: Scancode
SCANCODE_SOFTRIGHT: Scancode
SCANCODE_CALL: Scancode
SCANCODE_ENDCALL: Scancode
SCANCODE_RESERVED: Scancode
SCANCODE_COUNT: Scancode

class SystemTheme(metaclass=_pybind11_type):
    SYSTEM_THEME_UNKNOWN: ClassVar[SystemTheme]
    SYSTEM_THEME_LIGHT: ClassVar[SystemTheme]
    SYSTEM_THEME_DARK: ClassVar[SystemTheme]
    __members__: ClassVar[dict[str, SystemTheme]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class DisplayMode(metaclass=_pybind11_type):
    display_id: int
    format: Any
    w: int
    h: int
    pixel_density: float
    refresh_rate: float
    refresh_rate_numerator: int
    refresh_rate_denominator: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class DisplayOrientation(metaclass=_pybind11_type):
    ORIENTATION_UNKNOWN: ClassVar[DisplayOrientation]
    ORIENTATION_LANDSCAPE: ClassVar[DisplayOrientation]
    ORIENTATION_LANDSCAPE_FLIPPED: ClassVar[DisplayOrientation]
    ORIENTATION_PORTRAIT: ClassVar[DisplayOrientation]
    ORIENTATION_PORTRAIT_FLIPPED: ClassVar[DisplayOrientation]
    __members__: ClassVar[dict[str, DisplayOrientation]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class FlashOperation(metaclass=_pybind11_type):
    FLASH_CANCEL: ClassVar[FlashOperation]
    FLASH_BRIEFLY: ClassVar[FlashOperation]
    FLASH_UNTIL_FOCUSED: ClassVar[FlashOperation]
    __members__: ClassVar[dict[str, FlashOperation]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class ProgressState(metaclass=_pybind11_type):
    PROGRESS_STATE_INVALID: ClassVar[ProgressState]
    PROGRESS_STATE_NONE: ClassVar[ProgressState]
    PROGRESS_STATE_INDETERMINATE: ClassVar[ProgressState]
    PROGRESS_STATE_NORMAL: ClassVar[ProgressState]
    PROGRESS_STATE_PAUSED: ClassVar[ProgressState]
    PROGRESS_STATE_ERROR: ClassVar[ProgressState]
    __members__: ClassVar[dict[str, ProgressState]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class GLAttr(metaclass=_pybind11_type):
    GL_RED_SIZE: ClassVar[GLAttr]
    GL_GREEN_SIZE: ClassVar[GLAttr]
    GL_BLUE_SIZE: ClassVar[GLAttr]
    GL_ALPHA_SIZE: ClassVar[GLAttr]
    GL_BUFFER_SIZE: ClassVar[GLAttr]
    GL_DOUBLEBUFFER: ClassVar[GLAttr]
    GL_DEPTH_SIZE: ClassVar[GLAttr]
    GL_STENCIL_SIZE: ClassVar[GLAttr]
    GL_ACCUM_RED_SIZE: ClassVar[GLAttr]
    GL_ACCUM_GREEN_SIZE: ClassVar[GLAttr]
    GL_ACCUM_BLUE_SIZE: ClassVar[GLAttr]
    GL_ACCUM_ALPHA_SIZE: ClassVar[GLAttr]
    GL_STEREO: ClassVar[GLAttr]
    GL_MULTISAMPLEBUFFERS: ClassVar[GLAttr]
    GL_MULTISAMPLESAMPLES: ClassVar[GLAttr]
    GL_ACCELERATED_VISUAL: ClassVar[GLAttr]
    GL_RETAINED_BACKING: ClassVar[GLAttr]
    GL_CONTEXT_MAJOR_VERSION: ClassVar[GLAttr]
    GL_CONTEXT_MINOR_VERSION: ClassVar[GLAttr]
    GL_CONTEXT_FLAGS: ClassVar[GLAttr]
    GL_CONTEXT_PROFILE_MASK: ClassVar[GLAttr]
    GL_SHARE_WITH_CURRENT_CONTEXT: ClassVar[GLAttr]
    GL_FRAMEBUFFER_SRGB_CAPABLE: ClassVar[GLAttr]
    GL_CONTEXT_RELEASE_BEHAVIOR: ClassVar[GLAttr]
    GL_CONTEXT_RESET_NOTIFICATION: ClassVar[GLAttr]
    GL_CONTEXT_NO_ERROR: ClassVar[GLAttr]
    GL_FLOATBUFFERS: ClassVar[GLAttr]
    GL_EGL_PLATFORM: ClassVar[GLAttr]
    __members__: ClassVar[dict[str, GLAttr]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def get_num_video_drivers() -> int: ...
def get_video_driver(index: int) -> str: ...
def get_current_video_driver() -> str: ...
def get_system_theme() -> SystemTheme: ...
def get_displays(count: int) -> tuple[int, int]: ...
def get_primary_display() -> int: ...
def get_display_properties(display_id: int) -> int: ...
def get_display_name(display_id: int) -> str: ...
def get_display_bounds(display_id: int, rect: Any) -> bool: ...
def get_display_usable_bounds(display_id: int, rect: Any) -> bool: ...
def get_natural_display_orientation(display_id: int) -> DisplayOrientation: ...
def get_current_display_orientation(display_id: int) -> DisplayOrientation: ...
def get_display_content_scale(display_id: int) -> float: ...
def get_closest_fullscreen_display_mode(display_id: int, w: int, h: int, refresh_rate: float, include_high_density_modes: bool, closest: DisplayMode) -> bool: ...
def get_desktop_display_mode(display_id: int) -> DisplayMode: ...
def get_current_display_mode(display_id: int) -> DisplayMode: ...
def get_display_for_point(point: Any) -> int: ...
def get_display_for_rect(rect: Any) -> int: ...
def get_display_for_window(window: Any) -> int: ...
def get_window_pixel_density(window: Any) -> float: ...
def get_window_display_scale(window: Any) -> float: ...
def set_window_fullscreen_mode(window: Any, mode: DisplayMode) -> bool: ...
def get_window_fullscreen_mode(window: Any) -> DisplayMode: ...
def get_window_icc_profile(window: Any, size: int) -> tuple[Any, int]: ...
def get_window_pixel_format(window: Any) -> Any: ...
def create_window(title: str, w: int, h: int, flags: int) -> Any: ...
def create_popup_window(parent: Any, offset_x: int, offset_y: int, w: int, h: int, flags: int) -> Any: ...
def create_window_with_properties(props: int) -> Any: ...
def get_window_id(window: Any) -> int: ...
def get_window_from_id(id: int) -> Any: ...
def get_window_parent(window: Any) -> Any: ...
def get_window_properties(window: Any) -> int: ...
def get_window_flags(window: Any) -> int: ...
def set_window_title(window: Any, title: str) -> bool: ...
def get_window_title(window: Any) -> str: ...
def set_window_icon(window: Any, icon: Any) -> bool: ...
def set_window_position(window: Any, x: int, y: int) -> bool: ...
def get_window_position(window: Any, x: int, y: int) -> tuple[bool, int, int]: ...
def set_window_size(window: Any, w: int, h: int) -> bool: ...
def get_window_size(window: Any, w: int = ..., h: int = ...) -> tuple[int, int]: ...
def get_window_safe_area(window: Any, rect: Any) -> bool: ...
def set_window_aspect_ratio(window: Any, min_aspect: float, max_aspect: float) -> bool: ...
def get_window_aspect_ratio(window: Any, min_aspect: float, max_aspect: float) -> tuple[bool, float, float]: ...
def get_window_borders_size(window: Any, top: int, left: int, bottom: int, right: int) -> tuple[bool, int, int, int, int]: ...
def get_window_size_in_pixels(window: Any, w: int = ..., h: int = ...) -> tuple[int, int]: ...
def set_window_minimum_size(window: Any, min_w: int, min_h: int) -> bool: ...
def get_window_minimum_size(window: Any, w: int, h: int) -> tuple[bool, int, int]: ...
def set_window_maximum_size(window: Any, max_w: int, max_h: int) -> bool: ...
def get_window_maximum_size(window: Any, w: int, h: int) -> tuple[bool, int, int]: ...
def set_window_bordered(window: Any, bordered: bool) -> bool: ...
def set_window_resizable(window: Any, resizable: bool) -> bool: ...
def set_window_always_on_top(window: Any, on_top: bool) -> bool: ...
def set_window_fill_document(window: Any, fill: bool) -> bool: ...
def show_window(window: Any) -> bool: ...
def hide_window(window: Any) -> bool: ...
def raise_window(window: Any) -> bool: ...
def maximize_window(window: Any) -> bool: ...
def minimize_window(window: Any) -> bool: ...
def restore_window(window: Any) -> bool: ...
def set_window_fullscreen(window: Any, fullscreen: bool) -> bool: ...
def sync_window(window: Any) -> bool: ...
def window_has_surface(window: Any) -> bool: ...
def get_window_surface(window: Any) -> Any: ...
def set_window_surface_v_sync(window: Any, vsync: int) -> bool: ...
def get_window_surface_v_sync(window: Any, vsync: int) -> tuple[bool, int]: ...
def update_window_surface(window: Any) -> bool: ...
def update_window_surface_rects(window: Any, rects: Any, numrects: int) -> bool: ...
def destroy_window_surface(window: Any) -> bool: ...
def set_window_keyboard_grab(window: Any, grabbed: bool) -> bool: ...
def set_window_mouse_grab(window: Any, grabbed: bool) -> bool: ...
def get_window_keyboard_grab(window: Any) -> bool: ...
def get_window_mouse_grab(window: Any) -> bool: ...
def get_grabbed_window() -> Any: ...
def set_window_mouse_rect(window: Any, rect: Any) -> bool: ...
def get_window_mouse_rect(window: Any) -> Any: ...
def set_window_opacity(window: Any, opacity: float) -> bool: ...
def get_window_opacity(window: Any) -> float: ...
def set_window_parent(window: Any, parent: Any) -> bool: ...
def set_window_modal(window: Any, modal: bool) -> bool: ...
def set_window_focusable(window: Any, focusable: bool) -> bool: ...
def show_window_system_menu(window: Any, x: int, y: int) -> bool: ...
class HitTestResult(metaclass=_pybind11_type):
    HITTEST_NORMAL: ClassVar[HitTestResult]
    HITTEST_DRAGGABLE: ClassVar[HitTestResult]
    HITTEST_RESIZE_TOPLEFT: ClassVar[HitTestResult]
    HITTEST_RESIZE_TOP: ClassVar[HitTestResult]
    HITTEST_RESIZE_TOPRIGHT: ClassVar[HitTestResult]
    HITTEST_RESIZE_RIGHT: ClassVar[HitTestResult]
    HITTEST_RESIZE_BOTTOMRIGHT: ClassVar[HitTestResult]
    HITTEST_RESIZE_BOTTOM: ClassVar[HitTestResult]
    HITTEST_RESIZE_BOTTOMLEFT: ClassVar[HitTestResult]
    HITTEST_RESIZE_LEFT: ClassVar[HitTestResult]
    __members__: ClassVar[dict[str, HitTestResult]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def set_window_shape(window: Any, shape: Any) -> bool: ...
def flash_window(window: Any, operation: FlashOperation) -> bool: ...
def set_window_progress_state(window: Any, state: ProgressState) -> bool: ...
def get_window_progress_state(window: Any) -> ProgressState: ...
def set_window_progress_value(window: Any, value: float) -> bool: ...
def get_window_progress_value(window: Any) -> float: ...
def destroy_window(window: Any) -> None: ...
def screen_saver_enabled() -> bool: ...
def enable_screen_saver() -> bool: ...
def disable_screen_saver() -> bool: ...
def gl_load_library(path: str) -> bool: ...
def gl_unload_library() -> None: ...
def gl_extension_supported(extension: str) -> bool: ...
def gl_reset_attributes() -> None: ...
def gl_set_attribute(attr: GLAttr, value: int) -> bool: ...
def gl_get_attribute(attr: GLAttr, value: int) -> tuple[bool, int]: ...
def gl_get_current_window() -> Any: ...
def egl_get_current_display() -> Any: ...
def egl_get_current_config() -> Any: ...
def egl_get_window_surface(window: Any) -> Any: ...
def egl_set_attribute_callbacks(platform_attrib_callback: Callable[[Any], int], surface_attrib_callback: Callable[[Any, Any, Any], int], context_attrib_callback: Callable[[Any, Any, Any], int], userdata: Any) -> None: ...
def gl_set_swap_interval(interval: int) -> bool: ...
def gl_get_swap_interval(interval: int) -> tuple[bool, int]: ...
def gl_swap_window(window: Any) -> bool: ...
SYSTEM_THEME_UNKNOWN: SystemTheme
SYSTEM_THEME_LIGHT: SystemTheme
SYSTEM_THEME_DARK: SystemTheme
ORIENTATION_UNKNOWN: DisplayOrientation
ORIENTATION_LANDSCAPE: DisplayOrientation
ORIENTATION_LANDSCAPE_FLIPPED: DisplayOrientation
ORIENTATION_PORTRAIT: DisplayOrientation
ORIENTATION_PORTRAIT_FLIPPED: DisplayOrientation
FLASH_CANCEL: FlashOperation
FLASH_BRIEFLY: FlashOperation
FLASH_UNTIL_FOCUSED: FlashOperation
PROGRESS_STATE_INVALID: ProgressState
PROGRESS_STATE_NONE: ProgressState
PROGRESS_STATE_INDETERMINATE: ProgressState
PROGRESS_STATE_NORMAL: ProgressState
PROGRESS_STATE_PAUSED: ProgressState
PROGRESS_STATE_ERROR: ProgressState
GL_RED_SIZE: GLAttr
GL_GREEN_SIZE: GLAttr
GL_BLUE_SIZE: GLAttr
GL_ALPHA_SIZE: GLAttr
GL_BUFFER_SIZE: GLAttr
GL_DOUBLEBUFFER: GLAttr
GL_DEPTH_SIZE: GLAttr
GL_STENCIL_SIZE: GLAttr
GL_ACCUM_RED_SIZE: GLAttr
GL_ACCUM_GREEN_SIZE: GLAttr
GL_ACCUM_BLUE_SIZE: GLAttr
GL_ACCUM_ALPHA_SIZE: GLAttr
GL_STEREO: GLAttr
GL_MULTISAMPLEBUFFERS: GLAttr
GL_MULTISAMPLESAMPLES: GLAttr
GL_ACCELERATED_VISUAL: GLAttr
GL_RETAINED_BACKING: GLAttr
GL_CONTEXT_MAJOR_VERSION: GLAttr
GL_CONTEXT_MINOR_VERSION: GLAttr
GL_CONTEXT_FLAGS: GLAttr
GL_CONTEXT_PROFILE_MASK: GLAttr
GL_SHARE_WITH_CURRENT_CONTEXT: GLAttr
GL_FRAMEBUFFER_SRGB_CAPABLE: GLAttr
GL_CONTEXT_RELEASE_BEHAVIOR: GLAttr
GL_CONTEXT_RESET_NOTIFICATION: GLAttr
GL_CONTEXT_NO_ERROR: GLAttr
GL_FLOATBUFFERS: GLAttr
GL_EGL_PLATFORM: GLAttr
HITTEST_NORMAL: HitTestResult
HITTEST_DRAGGABLE: HitTestResult
HITTEST_RESIZE_TOPLEFT: HitTestResult
HITTEST_RESIZE_TOP: HitTestResult
HITTEST_RESIZE_TOPRIGHT: HitTestResult
HITTEST_RESIZE_RIGHT: HitTestResult
HITTEST_RESIZE_BOTTOMRIGHT: HitTestResult
HITTEST_RESIZE_BOTTOM: HitTestResult
HITTEST_RESIZE_BOTTOMLEFT: HitTestResult
HITTEST_RESIZE_LEFT: HitTestResult

class AudioFormat(metaclass=_pybind11_type):
    AUDIO_UNKNOWN: ClassVar[AudioFormat]
    AUDIO_U8: ClassVar[AudioFormat]
    AUDIO_S8: ClassVar[AudioFormat]
    AUDIO_S16_LE: ClassVar[AudioFormat]
    AUDIO_S16_BE: ClassVar[AudioFormat]
    AUDIO_S32_LE: ClassVar[AudioFormat]
    AUDIO_S32_BE: ClassVar[AudioFormat]
    AUDIO_F32_LE: ClassVar[AudioFormat]
    AUDIO_F32_BE: ClassVar[AudioFormat]
    AUDIO_S16: ClassVar[AudioFormat]
    AUDIO_S32: ClassVar[AudioFormat]
    AUDIO_F32: ClassVar[AudioFormat]
    __members__: ClassVar[dict[str, AudioFormat]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class AudioSpec(metaclass=_pybind11_type):
    format: AudioFormat
    channels: int
    freq: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def get_num_audio_drivers() -> int: ...
def get_audio_driver(index: int) -> str: ...
def get_current_audio_driver() -> str: ...
def get_audio_playback_devices(count: int) -> tuple[int, int]: ...
def get_audio_recording_devices(count: int) -> tuple[int, int]: ...
def get_audio_device_name(devid: int) -> str: ...
def get_audio_device_format(devid: int, spec: AudioSpec, sample_frames: int) -> tuple[bool, int]: ...
def get_audio_device_channel_map(devid: int, count: int) -> tuple[int, int]: ...
def get_audio_device_properties(devid: int) -> int: ...
def open_audio_device(devid: int, spec: AudioSpec) -> int: ...
def is_audio_device_physical(devid: int) -> bool: ...
def is_audio_device_playback(devid: int) -> bool: ...
def pause_audio_device(devid: int) -> bool: ...
def resume_audio_device(devid: int) -> bool: ...
def audio_device_paused(devid: int) -> bool: ...
def get_audio_device_gain(devid: int) -> float: ...
def set_audio_device_gain(devid: int, gain: float) -> bool: ...
def close_audio_device(devid: int) -> None: ...
def bind_audio_stream(devid: int, stream: Any) -> bool: ...
def unbind_audio_stream(stream: Any) -> None: ...
def get_audio_stream_device(stream: Any) -> int: ...
def create_audio_stream(src_spec: AudioSpec, dst_spec: AudioSpec) -> Any: ...
def get_audio_stream_properties(stream: Any) -> int: ...
def get_audio_stream_format(stream: Any, src_spec: AudioSpec, dst_spec: AudioSpec) -> bool: ...
def set_audio_stream_format(stream: Any, src_spec: AudioSpec, dst_spec: AudioSpec) -> bool: ...
def get_audio_stream_frequency_ratio(stream: Any) -> float: ...
def set_audio_stream_frequency_ratio(stream: Any, ratio: float) -> bool: ...
def get_audio_stream_gain(stream: Any) -> float: ...
def set_audio_stream_gain(stream: Any, gain: float) -> bool: ...
def get_audio_stream_input_channel_map(stream: Any, count: int) -> tuple[int, int]: ...
def get_audio_stream_output_channel_map(stream: Any, count: int) -> tuple[int, int]: ...
def set_audio_stream_input_channel_map(stream: Any, chmap: int, count: int) -> bool: ...
def set_audio_stream_output_channel_map(stream: Any, chmap: int, count: int) -> bool: ...
def put_audio_stream_data(stream: Any, buf: Any, len: int) -> bool: ...
def get_audio_stream_data(stream: Any, buf: Any, len: int) -> int: ...
def get_audio_stream_available(stream: Any) -> int: ...
def get_audio_stream_queued(stream: Any) -> int: ...
def flush_audio_stream(stream: Any) -> bool: ...
def clear_audio_stream(stream: Any) -> bool: ...
def pause_audio_stream_device(stream: Any) -> bool: ...
def resume_audio_stream_device(stream: Any) -> bool: ...
def audio_stream_device_paused(stream: Any) -> bool: ...
def lock_audio_stream(stream: Any) -> bool: ...
def unlock_audio_stream(stream: Any) -> bool: ...
def destroy_audio_stream(stream: Any) -> None: ...
def open_audio_device_stream(devid: int, spec: AudioSpec, callback: Callable[[Any, Any, int, int], None], userdata: Any) -> Any: ...
def set_audio_postmix_callback(devid: int, callback: Callable[[Any, AudioSpec, float, int], None], userdata: Any) -> bool: ...
def mix_audio(dst: int, src: int, format: AudioFormat, len: int, volume: float) -> bool: ...
def get_audio_format_name(format: AudioFormat) -> str: ...
def get_silence_value_for_format(format: AudioFormat) -> int: ...
AUDIO_UNKNOWN: AudioFormat
AUDIO_U8: AudioFormat
AUDIO_S8: AudioFormat
AUDIO_S16_LE: AudioFormat
AUDIO_S16_BE: AudioFormat
AUDIO_S32_LE: AudioFormat
AUDIO_S32_BE: AudioFormat
AUDIO_F32_LE: AudioFormat
AUDIO_F32_BE: AudioFormat
AUDIO_S16: AudioFormat
AUDIO_S32: AudioFormat
AUDIO_F32: AudioFormat

def version() -> int: ...
def init() -> bool: ...
def quit() -> None: ...
def get_num_audio_decoders() -> int: ...
def get_audio_decoder(index: int) -> str: ...
def create_mixer_device(devid: int, spec: Any) -> Any: ...
def create_mixer(spec: Any) -> Any: ...
def destroy_mixer(mixer: Any) -> None: ...
def get_mixer_properties(mixer: Any) -> int: ...
def get_mixer_format(mixer: Any, spec: Any) -> bool: ...
def lock_mixer(mixer: Any) -> None: ...
def unlock_mixer(mixer: Any) -> None: ...
def load_audio_io(mixer: Any, io: Any, predecode: bool, closeio: bool) -> Any: ...
def load_audio(mixer: Any, path: str, predecode: bool) -> Any: ...
def load_audio_no_copy(mixer: Any, data: Any, datalen: int, free_when_done: bool) -> Any: ...
def load_audio_with_properties(props: int) -> Any: ...
def load_raw_audio_io(mixer: Any, io: Any, spec: Any, closeio: bool) -> Any: ...
def load_raw_audio(mixer: Any, data: Any, datalen: int, spec: Any) -> Any: ...
def load_raw_audio_no_copy(mixer: Any, data: Any, datalen: int, spec: Any, free_when_done: bool) -> Any: ...
def create_sine_wave_audio(mixer: Any, hz: int, amplitude: float, ms: int) -> Any: ...
def get_audio_properties(audio: Any) -> int: ...
def get_audio_duration(audio: Any) -> int: ...
def get_audio_format(audio: Any, spec: Any) -> bool: ...
def destroy_audio(audio: Any) -> None: ...
def create_track(mixer: Any) -> Any: ...
def destroy_track(track: Any) -> None: ...
def get_track_properties(track: Any) -> int: ...
def get_track_mixer(track: Any) -> Any: ...
def set_track_audio(track: Any, audio: Any) -> bool: ...
def set_track_audio_stream(track: Any, stream: Any) -> bool: ...
def set_track_io_stream(track: Any, io: Any, closeio: bool) -> bool: ...
def set_track_raw_io_stream(track: Any, io: Any, spec: Any, closeio: bool) -> bool: ...
def tag_track(track: Any, tag: str) -> bool: ...
def untag_track(track: Any, tag: str) -> None: ...
def get_tagged_tracks(mixer: Any, tag: str, count: int) -> tuple[Any, int]: ...
def set_track_playback_position(track: Any, frames: int) -> bool: ...
def get_track_playback_position(track: Any) -> int: ...
def get_track_fade_frames(track: Any) -> int: ...
def get_track_loops(track: Any) -> int: ...
def set_track_loops(track: Any, num_loops: int) -> bool: ...
def get_track_audio(track: Any) -> Any: ...
def get_track_audio_stream(track: Any) -> Any: ...
def get_track_remaining(track: Any) -> int: ...
def track_ms_to_frames(track: Any, ms: int) -> int: ...
def track_frames_to_ms(track: Any, frames: int) -> int: ...
def audio_ms_to_frames(audio: Any, ms: int) -> int: ...
def audio_frames_to_ms(audio: Any, frames: int) -> int: ...
def ms_to_frames(sample_rate: int, ms: int) -> int: ...
def frames_to_ms(sample_rate: int, frames: int) -> int: ...
def play_track(track: Any, options: int) -> bool: ...
def play_tag(mixer: Any, tag: str, options: int) -> bool: ...
def play_audio(mixer: Any, audio: Any) -> bool: ...
def stop_track(track: Any, fade_out_frames: int) -> bool: ...
def stop_all_tracks(mixer: Any, fade_out_ms: int) -> bool: ...
def stop_tag(mixer: Any, tag: str, fade_out_ms: int) -> bool: ...
def pause_track(track: Any) -> bool: ...
def pause_all_tracks(mixer: Any) -> bool: ...
def pause_tag(mixer: Any, tag: str) -> bool: ...
def resume_track(track: Any) -> bool: ...
def resume_all_tracks(mixer: Any) -> bool: ...
def resume_tag(mixer: Any, tag: str) -> bool: ...
def track_playing(track: Any) -> bool: ...
def track_paused(track: Any) -> bool: ...
def set_mixer_gain(mixer: Any, gain: float) -> bool: ...
def get_mixer_gain(mixer: Any) -> float: ...
def set_track_gain(track: Any, gain: float) -> bool: ...
def get_track_gain(track: Any) -> float: ...
def set_tag_gain(mixer: Any, tag: str, gain: float) -> bool: ...
def set_mixer_frequency_ratio(mixer: Any, ratio: float) -> bool: ...
def get_mixer_frequency_ratio(mixer: Any) -> float: ...
def set_track_frequency_ratio(track: Any, ratio: float) -> bool: ...
def get_track_frequency_ratio(track: Any) -> float: ...
def set_track_output_channel_map(track: Any, chmap: int, count: int) -> bool: ...
class StereoGains(metaclass=_pybind11_type):
    left: float
    right: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def set_track_stereo(track: Any, gains: StereoGains) -> bool: ...
class Point3D(metaclass=_pybind11_type):
    x: float
    y: float
    z: float
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def set_track3_d_position(track: Any, position: Point3D) -> bool: ...
def get_track3_d_position(track: Any, position: Point3D) -> bool: ...
def create_group(mixer: Any) -> Any: ...
def destroy_group(group: Any) -> None: ...
def get_group_properties(group: Any) -> int: ...
def get_group_mixer(group: Any) -> Any: ...
def set_track_group(track: Any, group: Any) -> bool: ...
def set_track_stopped_callback(track: Any, cb: Callable[[Any, Any], None], userdata: Any) -> bool: ...
def set_track_raw_callback(track: Any, cb: Callable[[Any, Any, Any, float, int], None], userdata: Any) -> bool: ...
def set_track_cooked_callback(track: Any, cb: Callable[[Any, Any, Any, float, int], None], userdata: Any) -> bool: ...
def set_group_post_mix_callback(group: Any, cb: Callable[[Any, Any, Any, float, int], None], userdata: Any) -> bool: ...
def set_post_mix_callback(mixer: Any, cb: Callable[[Any, Any, Any, float, int], None], userdata: Any) -> bool: ...
def generate(mixer: Any, buffer: Any, buflen: int) -> int: ...
def create_audio_decoder(path: str, props: int) -> Any: ...
def create_audio_decoder_io(io: Any, closeio: bool, props: int) -> Any: ...
def destroy_audio_decoder(audiodecoder: Any) -> None: ...
def get_audio_decoder_properties(audiodecoder: Any) -> int: ...
def get_audio_decoder_format(audiodecoder: Any, spec: Any) -> bool: ...
def decode_audio(audiodecoder: Any, buffer: Any, buflen: int, spec: Any) -> int: ...
