#from enum import Enum

#class WindowProperties(Enum):
class WindowProperties:
    ANDROID_WINDOW_POINTER = "SDL.window.android.window"
    ANDROID_SURFACE_POINTER = "SDL.window.android.surface"
    UIKIT_WINDOW_POINTER = "SDL.window.uikit.window"
    UIKIT_METAL_VIEW_TAG_NUMBER = "SDL.window.uikit.metal_view_tag"
    KMSDRM_DEVICE_INDEX_NUMBER = "SDL.window.kmsdrm.dev_index"
    KMSDRM_DRM_FD_NUMBER = "SDL.window.kmsdrm.drm_fd"
    KMSDRM_GBM_DEVICE_POINTER = "SDL.window.kmsdrm.gbm_dev"
    COCOA_WINDOW_POINTER = "SDL.window.cocoa.window"
    COCOA_METAL_VIEW_TAG_NUMBER = "SDL.window.cocoa.metal_view_tag"
    VIVANTE_DISPLAY_POINTER = "SDL.window.vivante.display"
    VIVANTE_WINDOW_POINTER = "SDL.window.vivante.window"
    VIVANTE_SURFACE_POINTER = "SDL.window.vivante.surface"
    WINRT_WINDOW_POINTER = "SDL.window.winrt.window"
    WIN32_HWND_POINTER = "SDL.window.win32.hwnd"
    WIN32_HDC_POINTER = "SDL.window.win32.hdc"
    WIN32_INSTANCE_POINTER = "SDL.window.win32.instance"
    WAYLAND_DISPLAY_POINTER = "SDL.window.wayland.display"
    WAYLAND_SURFACE_POINTER = "SDL.window.wayland.surface"
    WAYLAND_EGL_WINDOW_POINTER = "SDL.window.wayland.egl_window"
    WAYLAND_XDG_SURFACE_POINTER = "SDL.window.wayland.xdg_surface"
    WAYLAND_XDG_TOPLEVEL_POINTER = "SDL.window.wayland.xdg_toplevel"
    WAYLAND_XDG_POPUP_POINTER = "SDL.window.wayland.xdg_popup"
    WAYLAND_XDG_POSITIONER_POINTER = "SDL.window.wayland.xdg_positioner"
    X11_DISPLAY_POINTER = "SDL.window.x11.display"
    X11_SCREEN_NUMBER = "SDL.window.x11.screen"
    X11_WINDOW_NUMBER = "SDL.window.x11.window"
