module: _sdl

flags: [
  '-x', 'c++',
  '-std=c++17',
  '-I../../depot/sdl/include',
]

prefixes: [SDL_]

unit_files:
  - path: sdl_events.yaml
  - path: sdl_init.yaml
  - path: sdl_keyboard.yaml
  - path: sdl_mouse.yaml
  - path: sdl_properties.yaml
  - path: sdl_scancode.yaml
  - path: sdl_video.yaml