from crunge import sdl
from crunge.imgui import Key

key_map = {
    # Alphanumeric keys
    sdl.SDLK_a: Key.KEY_A,
    sdl.SDLK_b: Key.KEY_B,
    sdl.SDLK_c: Key.KEY_C,
    sdl.SDLK_d: Key.KEY_D,
    sdl.SDLK_e: Key.KEY_E,
    sdl.SDLK_f: Key.KEY_F,
    sdl.SDLK_g: Key.KEY_G,
    sdl.SDLK_h: Key.KEY_H,
    sdl.SDLK_i: Key.KEY_I,
    sdl.SDLK_j: Key.KEY_J,
    sdl.SDLK_k: Key.KEY_K,
    sdl.SDLK_l: Key.KEY_L,
    sdl.SDLK_m: Key.KEY_M,
    sdl.SDLK_n: Key.KEY_N,
    sdl.SDLK_o: Key.KEY_O,
    sdl.SDLK_p: Key.KEY_P,
    sdl.SDLK_q: Key.KEY_Q,
    sdl.SDLK_r: Key.KEY_R,
    sdl.SDLK_s: Key.KEY_S,
    sdl.SDLK_t: Key.KEY_T,
    sdl.SDLK_u: Key.KEY_U,
    sdl.SDLK_v: Key.KEY_V,
    sdl.SDLK_w: Key.KEY_W,
    sdl.SDLK_x: Key.KEY_X,
    sdl.SDLK_y: Key.KEY_Y,
    sdl.SDLK_z: Key.KEY_Z,
    
    sdl.SDLK_0: Key.KEY_0,
    sdl.SDLK_1: Key.KEY_1,
    sdl.SDLK_2: Key.KEY_2,
    sdl.SDLK_3: Key.KEY_3,
    sdl.SDLK_4: Key.KEY_4,
    sdl.SDLK_5: Key.KEY_5,
    sdl.SDLK_6: Key.KEY_6,
    sdl.SDLK_7: Key.KEY_7,
    sdl.SDLK_8: Key.KEY_8,
    sdl.SDLK_9: Key.KEY_9,
    
    # Function keys
    sdl.SDLK_F1: Key.KEY_F1,
    sdl.SDLK_F2: Key.KEY_F2,
    sdl.SDLK_F3: Key.KEY_F3,
    sdl.SDLK_F4: Key.KEY_F4,
    sdl.SDLK_F5: Key.KEY_F5,
    sdl.SDLK_F6: Key.KEY_F6,
    sdl.SDLK_F7: Key.KEY_F7,
    sdl.SDLK_F8: Key.KEY_F8,
    sdl.SDLK_F9: Key.KEY_F9,
    sdl.SDLK_F10: Key.KEY_F10,
    sdl.SDLK_F11: Key.KEY_F11,
    sdl.SDLK_F12: Key.KEY_F12,
    
    # Special keys
    sdl.SDLK_TAB: Key.KEY_TAB,
    sdl.SDLK_LEFT: Key.KEY_LEFT_ARROW,
    sdl.SDLK_RIGHT: Key.KEY_RIGHT_ARROW,
    sdl.SDLK_UP: Key.KEY_UP_ARROW,
    sdl.SDLK_DOWN: Key.KEY_DOWN_ARROW,
    sdl.SDLK_PAGEUP: Key.KEY_PAGE_UP,
    sdl.SDLK_PAGEDOWN: Key.KEY_PAGE_DOWN,
    sdl.SDLK_HOME: Key.KEY_HOME,
    sdl.SDLK_END: Key.KEY_END,
    sdl.SDLK_INSERT: Key.KEY_INSERT,
    sdl.SDLK_DELETE: Key.KEY_DELETE,
    sdl.SDLK_BACKSPACE: Key.KEY_BACKSPACE,
    sdl.SDLK_SPACE: Key.KEY_SPACE,
    sdl.SDLK_RETURN: Key.KEY_ENTER,
    sdl.SDLK_ESCAPE: Key.KEY_ESCAPE,
    
    # Keypad
    sdl.SDLK_KP_0: Key.KEY_KEYPAD0,
    sdl.SDLK_KP_1: Key.KEY_KEYPAD1,
    sdl.SDLK_KP_2: Key.KEY_KEYPAD2,
    sdl.SDLK_KP_3: Key.KEY_KEYPAD3,
    sdl.SDLK_KP_4: Key.KEY_KEYPAD4,
    sdl.SDLK_KP_5: Key.KEY_KEYPAD5,
    sdl.SDLK_KP_6: Key.KEY_KEYPAD6,
    sdl.SDLK_KP_7: Key.KEY_KEYPAD7,
    sdl.SDLK_KP_8: Key.KEY_KEYPAD8,
    sdl.SDLK_KP_9: Key.KEY_KEYPAD9,
    sdl.SDLK_KP_DECIMAL: Key.KEY_KEYPAD_DECIMAL,
    sdl.SDLK_KP_DIVIDE: Key.KEY_KEYPAD_DIVIDE,
    sdl.SDLK_KP_MULTIPLY: Key.KEY_KEYPAD_MULTIPLY,
    sdl.SDLK_KP_MINUS: Key.KEY_KEYPAD_SUBTRACT,
    sdl.SDLK_KP_PLUS: Key.KEY_KEYPAD_ADD,
    sdl.SDLK_KP_ENTER: Key.KEY_KEYPAD_ENTER,
    
    # Control keys
    sdl.SDLK_LCTRL: Key.KEY_LEFT_CTRL,
    sdl.SDLK_LSHIFT: Key.KEY_LEFT_SHIFT,
    sdl.SDLK_LALT: Key.KEY_LEFT_ALT,
    sdl.SDLK_LGUI: Key.KEY_LEFT_SUPER,
    sdl.SDLK_RCTRL: Key.KEY_RIGHT_CTRL,
    sdl.SDLK_RSHIFT: Key.KEY_RIGHT_SHIFT,
    sdl.SDLK_RALT: Key.KEY_RIGHT_ALT,
    sdl.SDLK_RGUI: Key.KEY_RIGHT_SUPER,
    sdl.SDLK_MENU: Key.KEY_MENU,
    
    # Additional keys
    sdl.SDLK_CAPSLOCK: Key.KEY_CAPS_LOCK,
    sdl.SDLK_PRINTSCREEN: Key.KEY_PRINT_SCREEN,
    sdl.SDLK_SCROLLLOCK: Key.KEY_SCROLL_LOCK,
    sdl.SDLK_PAUSE: Key.KEY_PAUSE,
    sdl.SDLK_NUMLOCKCLEAR: Key.KEY_NUM_LOCK,
    
    # Punctuation and symbols
    sdl.SDLK_MINUS: Key.KEY_MINUS,
    sdl.SDLK_EQUALS: Key.KEY_EQUAL,
    sdl.SDLK_LEFTBRACKET: Key.KEY_LEFT_BRACKET,
    sdl.SDLK_RIGHTBRACKET: Key.KEY_RIGHT_BRACKET,
    sdl.SDLK_BACKSLASH: Key.KEY_BACKSLASH,
    sdl.SDLK_SEMICOLON: Key.KEY_SEMICOLON,
    sdl.SDLK_QUOTE: Key.KEY_APOSTROPHE,
    sdl.SDLK_COMMA: Key.KEY_COMMA,
    sdl.SDLK_PERIOD: Key.KEY_PERIOD,
    sdl.SDLK_SLASH: Key.KEY_SLASH,
    sdl.SDLK_BACKQUOTE: Key.KEY_GRAVE_ACCENT,
}