from crunge import sdl
from crunge.imgui import Key

key_map = {
    # Alphanumeric keys
    sdl.SDLK_a: Key.A,
    sdl.SDLK_b: Key.B,
    sdl.SDLK_c: Key.C,
    sdl.SDLK_d: Key.D,
    sdl.SDLK_e: Key.E,
    sdl.SDLK_f: Key.F,
    sdl.SDLK_g: Key.G,
    sdl.SDLK_h: Key.H,
    sdl.SDLK_i: Key.I,
    sdl.SDLK_j: Key.J,
    sdl.SDLK_k: Key.K,
    sdl.SDLK_l: Key.L,
    sdl.SDLK_m: Key.M,
    sdl.SDLK_n: Key.N,
    sdl.SDLK_o: Key.O,
    sdl.SDLK_p: Key.P,
    sdl.SDLK_q: Key.Q,
    sdl.SDLK_r: Key.R,
    sdl.SDLK_s: Key.S,
    sdl.SDLK_t: Key.T,
    sdl.SDLK_u: Key.U,
    sdl.SDLK_v: Key.V,
    sdl.SDLK_w: Key.W,
    sdl.SDLK_x: Key.X,
    sdl.SDLK_y: Key.Y,
    sdl.SDLK_z: Key.Z,
    
    sdl.SDLK_0: Key.KEY_0,
    sdl.SDLK_1: Key.KEY_1,
    sdl.SDLK_2: Key.KEY_2,
    sdl.SDLK_3: Key.KEY_3,
    sdl.SDLK_4: Key.KEY_4,
    sdl.SDLK_5: Key.KEY_5,
    sdl.SDLK_6: Key.KEY_6,
    sdl.SDLK_7: Key.KEY_7,
    sdl.SDLK_8: Key.KEY_8,
    sdl.SDLK_9: Key.KEY_9,
    
    # Function keys
    sdl.SDLK_F1: Key.F1,
    sdl.SDLK_F2: Key.F2,
    sdl.SDLK_F3: Key.F3,
    sdl.SDLK_F4: Key.F4,
    sdl.SDLK_F5: Key.F5,
    sdl.SDLK_F6: Key.F6,
    sdl.SDLK_F7: Key.F7,
    sdl.SDLK_F8: Key.F8,
    sdl.SDLK_F9: Key.F9,
    sdl.SDLK_F10: Key.F10,
    sdl.SDLK_F11: Key.F11,
    sdl.SDLK_F12: Key.F12,
    
    # Special keys
    sdl.SDLK_TAB: Key.TAB,
    sdl.SDLK_LEFT: Key.LEFT_ARROW,
    sdl.SDLK_RIGHT: Key.RIGHT_ARROW,
    sdl.SDLK_UP: Key.UP_ARROW,
    sdl.SDLK_DOWN: Key.DOWN_ARROW,
    sdl.SDLK_PAGEUP: Key.PAGE_UP,
    sdl.SDLK_PAGEDOWN: Key.PAGE_DOWN,
    sdl.SDLK_HOME: Key.HOME,
    sdl.SDLK_END: Key.END,
    sdl.SDLK_INSERT: Key.INSERT,
    sdl.SDLK_DELETE: Key.DELETE,
    sdl.SDLK_BACKSPACE: Key.BACKSPACE,
    sdl.SDLK_SPACE: Key.SPACE,
    sdl.SDLK_RETURN: Key.ENTER,
    sdl.SDLK_ESCAPE: Key.ESCAPE,
    
    # Keypad
    sdl.SDLK_KP_0: Key.KEYPAD0,
    sdl.SDLK_KP_1: Key.KEYPAD1,
    sdl.SDLK_KP_2: Key.KEYPAD2,
    sdl.SDLK_KP_3: Key.KEYPAD3,
    sdl.SDLK_KP_4: Key.KEYPAD4,
    sdl.SDLK_KP_5: Key.KEYPAD5,
    sdl.SDLK_KP_6: Key.KEYPAD6,
    sdl.SDLK_KP_7: Key.KEYPAD7,
    sdl.SDLK_KP_8: Key.KEYPAD8,
    sdl.SDLK_KP_9: Key.KEYPAD9,
    sdl.SDLK_KP_DECIMAL: Key.KEYPAD_DECIMAL,
    sdl.SDLK_KP_DIVIDE: Key.KEYPAD_DIVIDE,
    sdl.SDLK_KP_MULTIPLY: Key.KEYPAD_MULTIPLY,
    sdl.SDLK_KP_MINUS: Key.KEYPAD_SUBTRACT,
    sdl.SDLK_KP_PLUS: Key.KEYPAD_ADD,
    sdl.SDLK_KP_ENTER: Key.KEYPAD_ENTER,
    
    # Control keys
    sdl.SDLK_LCTRL: Key.LEFT_CTRL,
    sdl.SDLK_LSHIFT: Key.LEFT_SHIFT,
    sdl.SDLK_LALT: Key.LEFT_ALT,
    sdl.SDLK_LGUI: Key.LEFT_SUPER,
    sdl.SDLK_RCTRL: Key.RIGHT_CTRL,
    sdl.SDLK_RSHIFT: Key.RIGHT_SHIFT,
    sdl.SDLK_RALT: Key.RIGHT_ALT,
    sdl.SDLK_RGUI: Key.RIGHT_SUPER,
    sdl.SDLK_MENU: Key.MENU,
    
    # Additional keys
    sdl.SDLK_CAPSLOCK: Key.CAPS_LOCK,
    sdl.SDLK_PRINTSCREEN: Key.PRINT_SCREEN,
    sdl.SDLK_SCROLLLOCK: Key.SCROLL_LOCK,
    sdl.SDLK_PAUSE: Key.PAUSE,
    sdl.SDLK_NUMLOCKCLEAR: Key.NUM_LOCK,
    
    # Punctuation and symbols
    sdl.SDLK_MINUS: Key.MINUS,
    sdl.SDLK_EQUALS: Key.EQUAL,
    sdl.SDLK_LEFTBRACKET: Key.LEFT_BRACKET,
    sdl.SDLK_RIGHTBRACKET: Key.RIGHT_BRACKET,
    sdl.SDLK_BACKSLASH: Key.BACKSLASH,
    sdl.SDLK_SEMICOLON: Key.SEMICOLON,
    sdl.SDLK_QUOTE: Key.APOSTROPHE,
    sdl.SDLK_COMMA: Key.COMMA,
    sdl.SDLK_PERIOD: Key.PERIOD,
    sdl.SDLK_SLASH: Key.SLASH,
    sdl.SDLK_BACKQUOTE: Key.GRAVE_ACCENT,
}