from crunge.sdl import Scancode
from crunge.imgui import Key

scancode_map = {
    # Alphanumeric keys
    Scancode.SCANCODE_A: Key.KEY_A,
    Scancode.SCANCODE_B: Key.KEY_B,
    Scancode.SCANCODE_C: Key.KEY_C,
    Scancode.SCANCODE_D: Key.KEY_D,
    Scancode.SCANCODE_E: Key.KEY_E,
    Scancode.SCANCODE_F: Key.KEY_F,
    Scancode.SCANCODE_G: Key.KEY_G,
    Scancode.SCANCODE_H: Key.KEY_H,
    Scancode.SCANCODE_I: Key.KEY_I,
    Scancode.SCANCODE_J: Key.KEY_J,
    Scancode.SCANCODE_K: Key.KEY_K,
    Scancode.SCANCODE_L: Key.KEY_L,
    Scancode.SCANCODE_M: Key.KEY_M,
    Scancode.SCANCODE_N: Key.KEY_N,
    Scancode.SCANCODE_O: Key.KEY_O,
    Scancode.SCANCODE_P: Key.KEY_P,
    Scancode.SCANCODE_Q: Key.KEY_Q,
    Scancode.SCANCODE_R: Key.KEY_R,
    Scancode.SCANCODE_S: Key.KEY_S,
    Scancode.SCANCODE_T: Key.KEY_T,
    Scancode.SCANCODE_U: Key.KEY_U,
    Scancode.SCANCODE_V: Key.KEY_V,
    Scancode.SCANCODE_W: Key.KEY_W,
    Scancode.SCANCODE_X: Key.KEY_X,
    Scancode.SCANCODE_Y: Key.KEY_Y,
    Scancode.SCANCODE_Z: Key.KEY_Z,
    
    Scancode.SCANCODE_0: Key.KEY_0,
    Scancode.SCANCODE_1: Key.KEY_1,
    Scancode.SCANCODE_2: Key.KEY_2,
    Scancode.SCANCODE_3: Key.KEY_3,
    Scancode.SCANCODE_4: Key.KEY_4,
    Scancode.SCANCODE_5: Key.KEY_5,
    Scancode.SCANCODE_6: Key.KEY_6,
    Scancode.SCANCODE_7: Key.KEY_7,
    Scancode.SCANCODE_8: Key.KEY_8,
    Scancode.SCANCODE_9: Key.KEY_9,
    
    # Function keys
    Scancode.SCANCODE_F1: Key.KEY_F1,
    Scancode.SCANCODE_F2: Key.KEY_F2,
    Scancode.SCANCODE_F3: Key.KEY_F3,
    Scancode.SCANCODE_F4: Key.KEY_F4,
    Scancode.SCANCODE_F5: Key.KEY_F5,
    Scancode.SCANCODE_F6: Key.KEY_F6,
    Scancode.SCANCODE_F7: Key.KEY_F7,
    Scancode.SCANCODE_F8: Key.KEY_F8,
    Scancode.SCANCODE_F9: Key.KEY_F9,
    Scancode.SCANCODE_F10: Key.KEY_F10,
    Scancode.SCANCODE_F11: Key.KEY_F11,
    Scancode.SCANCODE_F12: Key.KEY_F12,
    
    # Special keys
    Scancode.SCANCODE_TAB: Key.KEY_TAB,
    Scancode.SCANCODE_LEFT: Key.KEY_LEFT_ARROW,
    Scancode.SCANCODE_RIGHT: Key.KEY_RIGHT_ARROW,
    Scancode.SCANCODE_UP: Key.KEY_UP_ARROW,
    Scancode.SCANCODE_DOWN: Key.KEY_DOWN_ARROW,
    Scancode.SCANCODE_PAGEUP: Key.KEY_PAGE_UP,
    Scancode.SCANCODE_PAGEDOWN: Key.KEY_PAGE_DOWN,
    Scancode.SCANCODE_HOME: Key.KEY_HOME,
    Scancode.SCANCODE_END: Key.KEY_END,
    Scancode.SCANCODE_INSERT: Key.KEY_INSERT,
    Scancode.SCANCODE_DELETE: Key.KEY_DELETE,
    Scancode.SCANCODE_BACKSPACE: Key.KEY_BACKSPACE,
    Scancode.SCANCODE_SPACE: Key.KEY_SPACE,
    Scancode.SCANCODE_RETURN: Key.KEY_ENTER,
    Scancode.SCANCODE_ESCAPE: Key.KEY_ESCAPE,
    
    # Keypad
    Scancode.SCANCODE_KP_0: Key.KEY_KEYPAD0,
    Scancode.SCANCODE_KP_1: Key.KEY_KEYPAD1,
    Scancode.SCANCODE_KP_2: Key.KEY_KEYPAD2,
    Scancode.SCANCODE_KP_3: Key.KEY_KEYPAD3,
    Scancode.SCANCODE_KP_4: Key.KEY_KEYPAD4,
    Scancode.SCANCODE_KP_5: Key.KEY_KEYPAD5,
    Scancode.SCANCODE_KP_6: Key.KEY_KEYPAD6,
    Scancode.SCANCODE_KP_7: Key.KEY_KEYPAD7,
    Scancode.SCANCODE_KP_8: Key.KEY_KEYPAD8,
    Scancode.SCANCODE_KP_9: Key.KEY_KEYPAD9,
    Scancode.SCANCODE_KP_DECIMAL: Key.KEY_KEYPAD_DECIMAL,
    Scancode.SCANCODE_KP_DIVIDE: Key.KEY_KEYPAD_DIVIDE,
    Scancode.SCANCODE_KP_MULTIPLY: Key.KEY_KEYPAD_MULTIPLY,
    Scancode.SCANCODE_KP_MINUS: Key.KEY_KEYPAD_SUBTRACT,
    Scancode.SCANCODE_KP_PLUS: Key.KEY_KEYPAD_ADD,
    Scancode.SCANCODE_KP_ENTER: Key.KEY_KEYPAD_ENTER,
    
    # Control keys
    Scancode.SCANCODE_LCTRL: Key.KEY_LEFT_CTRL,
    Scancode.SCANCODE_LSHIFT: Key.KEY_LEFT_SHIFT,
    Scancode.SCANCODE_LALT: Key.KEY_LEFT_ALT,
    Scancode.SCANCODE_LGUI: Key.KEY_LEFT_SUPER,
    Scancode.SCANCODE_RCTRL: Key.KEY_RIGHT_CTRL,
    Scancode.SCANCODE_RSHIFT: Key.KEY_RIGHT_SHIFT,
    Scancode.SCANCODE_RALT: Key.KEY_RIGHT_ALT,
    Scancode.SCANCODE_RGUI: Key.KEY_RIGHT_SUPER,
    Scancode.SCANCODE_MENU: Key.KEY_MENU,
    
    # Additional keys
    Scancode.SCANCODE_CAPSLOCK: Key.KEY_CAPS_LOCK,
    Scancode.SCANCODE_PRINTSCREEN: Key.KEY_PRINT_SCREEN,
    Scancode.SCANCODE_SCROLLLOCK: Key.KEY_SCROLL_LOCK,
    Scancode.SCANCODE_PAUSE: Key.KEY_PAUSE,
    Scancode.SCANCODE_NUMLOCKCLEAR: Key.KEY_NUM_LOCK,
    
    # Punctuation and symbols
    Scancode.SCANCODE_MINUS: Key.KEY_MINUS,
    Scancode.SCANCODE_EQUALS: Key.KEY_EQUAL,
    Scancode.SCANCODE_LEFTBRACKET: Key.KEY_LEFT_BRACKET,
    Scancode.SCANCODE_RIGHTBRACKET: Key.KEY_RIGHT_BRACKET,
    Scancode.SCANCODE_BACKSLASH: Key.KEY_BACKSLASH,
    Scancode.SCANCODE_SEMICOLON: Key.KEY_SEMICOLON,
    Scancode.SCANCODE_APOSTROPHE: Key.KEY_APOSTROPHE,
    Scancode.SCANCODE_COMMA: Key.KEY_COMMA,
    Scancode.SCANCODE_PERIOD: Key.KEY_PERIOD,
    Scancode.SCANCODE_SLASH: Key.KEY_SLASH,
    Scancode.SCANCODE_GRAVE: Key.KEY_GRAVE_ACCENT,
}