from crunge.sdl import Scancode
from crunge.imgui import Key

scancode_map = {
    # Alphanumeric keys
    Scancode.SCANCODE_A: Key.A,
    Scancode.SCANCODE_B: Key.B,
    Scancode.SCANCODE_C: Key.C,
    Scancode.SCANCODE_D: Key.D,
    Scancode.SCANCODE_E: Key.E,
    Scancode.SCANCODE_F: Key.F,
    Scancode.SCANCODE_G: Key.G,
    Scancode.SCANCODE_H: Key.H,
    Scancode.SCANCODE_I: Key.I,
    Scancode.SCANCODE_J: Key.J,
    Scancode.SCANCODE_K: Key.K,
    Scancode.SCANCODE_L: Key.L,
    Scancode.SCANCODE_M: Key.M,
    Scancode.SCANCODE_N: Key.N,
    Scancode.SCANCODE_O: Key.O,
    Scancode.SCANCODE_P: Key.P,
    Scancode.SCANCODE_Q: Key.Q,
    Scancode.SCANCODE_R: Key.R,
    Scancode.SCANCODE_S: Key.S,
    Scancode.SCANCODE_T: Key.T,
    Scancode.SCANCODE_U: Key.U,
    Scancode.SCANCODE_V: Key.V,
    Scancode.SCANCODE_W: Key.W,
    Scancode.SCANCODE_X: Key.X,
    Scancode.SCANCODE_Y: Key.Y,
    Scancode.SCANCODE_Z: Key.Z,
    
    Scancode.SCANCODE_0: Key.KEY_0,
    Scancode.SCANCODE_1: Key.KEY_1,
    Scancode.SCANCODE_2: Key.KEY_2,
    Scancode.SCANCODE_3: Key.KEY_3,
    Scancode.SCANCODE_4: Key.KEY_4,
    Scancode.SCANCODE_5: Key.KEY_5,
    Scancode.SCANCODE_6: Key.KEY_6,
    Scancode.SCANCODE_7: Key.KEY_7,
    Scancode.SCANCODE_8: Key.KEY_8,
    Scancode.SCANCODE_9: Key.KEY_9,
    
    # Function keys
    Scancode.SCANCODE_F1: Key.F1,
    Scancode.SCANCODE_F2: Key.F2,
    Scancode.SCANCODE_F3: Key.F3,
    Scancode.SCANCODE_F4: Key.F4,
    Scancode.SCANCODE_F5: Key.F5,
    Scancode.SCANCODE_F6: Key.F6,
    Scancode.SCANCODE_F7: Key.F7,
    Scancode.SCANCODE_F8: Key.F8,
    Scancode.SCANCODE_F9: Key.F9,
    Scancode.SCANCODE_F10: Key.F10,
    Scancode.SCANCODE_F11: Key.F11,
    Scancode.SCANCODE_F12: Key.F12,
    
    # Special keys
    Scancode.SCANCODE_TAB: Key.TAB,
    Scancode.SCANCODE_LEFT: Key.LEFT_ARROW,
    Scancode.SCANCODE_RIGHT: Key.RIGHT_ARROW,
    Scancode.SCANCODE_UP: Key.UP_ARROW,
    Scancode.SCANCODE_DOWN: Key.DOWN_ARROW,
    Scancode.SCANCODE_PAGEUP: Key.PAGE_UP,
    Scancode.SCANCODE_PAGEDOWN: Key.PAGE_DOWN,
    Scancode.SCANCODE_HOME: Key.HOME,
    Scancode.SCANCODE_END: Key.END,
    Scancode.SCANCODE_INSERT: Key.INSERT,
    Scancode.SCANCODE_DELETE: Key.DELETE,
    Scancode.SCANCODE_BACKSPACE: Key.BACKSPACE,
    Scancode.SCANCODE_SPACE: Key.SPACE,
    Scancode.SCANCODE_RETURN: Key.ENTER,
    Scancode.SCANCODE_ESCAPE: Key.ESCAPE,
    
    # Keypad
    Scancode.SCANCODE_KP_0: Key.KEYPAD0,
    Scancode.SCANCODE_KP_1: Key.KEYPAD1,
    Scancode.SCANCODE_KP_2: Key.KEYPAD2,
    Scancode.SCANCODE_KP_3: Key.KEYPAD3,
    Scancode.SCANCODE_KP_4: Key.KEYPAD4,
    Scancode.SCANCODE_KP_5: Key.KEYPAD5,
    Scancode.SCANCODE_KP_6: Key.KEYPAD6,
    Scancode.SCANCODE_KP_7: Key.KEYPAD7,
    Scancode.SCANCODE_KP_8: Key.KEYPAD8,
    Scancode.SCANCODE_KP_9: Key.KEYPAD9,
    Scancode.SCANCODE_KP_DECIMAL: Key.KEYPAD_DECIMAL,
    Scancode.SCANCODE_KP_DIVIDE: Key.KEYPAD_DIVIDE,
    Scancode.SCANCODE_KP_MULTIPLY: Key.KEYPAD_MULTIPLY,
    Scancode.SCANCODE_KP_MINUS: Key.KEYPAD_SUBTRACT,
    Scancode.SCANCODE_KP_PLUS: Key.KEYPAD_ADD,
    Scancode.SCANCODE_KP_ENTER: Key.KEYPAD_ENTER,
    
    # Control keys
    Scancode.SCANCODE_LCTRL: Key.LEFT_CTRL,
    Scancode.SCANCODE_LSHIFT: Key.LEFT_SHIFT,
    Scancode.SCANCODE_LALT: Key.LEFT_ALT,
    Scancode.SCANCODE_LGUI: Key.LEFT_SUPER,
    Scancode.SCANCODE_RCTRL: Key.RIGHT_CTRL,
    Scancode.SCANCODE_RSHIFT: Key.RIGHT_SHIFT,
    Scancode.SCANCODE_RALT: Key.RIGHT_ALT,
    Scancode.SCANCODE_RGUI: Key.RIGHT_SUPER,
    Scancode.SCANCODE_MENU: Key.MENU,
    
    # Additional keys
    Scancode.SCANCODE_CAPSLOCK: Key.CAPS_LOCK,
    Scancode.SCANCODE_PRINTSCREEN: Key.PRINT_SCREEN,
    Scancode.SCANCODE_SCROLLLOCK: Key.SCROLL_LOCK,
    Scancode.SCANCODE_PAUSE: Key.PAUSE,
    Scancode.SCANCODE_NUMLOCKCLEAR: Key.NUM_LOCK,
    
    # Punctuation and symbols
    Scancode.SCANCODE_MINUS: Key.MINUS,
    Scancode.SCANCODE_EQUALS: Key.EQUAL,
    Scancode.SCANCODE_LEFTBRACKET: Key.LEFT_BRACKET,
    Scancode.SCANCODE_RIGHTBRACKET: Key.RIGHT_BRACKET,
    Scancode.SCANCODE_BACKSLASH: Key.BACKSLASH,
    Scancode.SCANCODE_SEMICOLON: Key.SEMICOLON,
    Scancode.SCANCODE_APOSTROPHE: Key.APOSTROPHE,
    Scancode.SCANCODE_COMMA: Key.COMMA,
    Scancode.SCANCODE_PERIOD: Key.PERIOD,
    Scancode.SCANCODE_SLASH: Key.SLASH,
    Scancode.SCANCODE_GRAVE: Key.GRAVE_ACCENT,
}