[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "canvasdemo"
version = "0.1.0"
description = 'Crunge Canvas Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
]

[project.scripts]
canvasdemo = 'canvasdemo.cli:cli'

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # KCore
  "../../../kcore",

  # Crunge packages
  "../../pkg/core", "../../pkg/imgui", "../../pkg/wgpu", "../../pkg/skia", "../../pkg/yoga",
  "../../pkg/sdl",
  "../../pkg/engine", "../../pkg/demo",
]
dependencies = ["uv", "pytest", "mypy"]
