# Generated by cxbind. Do not edit.
from collections.abc import Callable
from typing import Any, ClassVar, overload

class _pybind11_type(type): ...  # stand-in for pybind11's metaclass

class Type(metaclass=_pybind11_type):
    NULL_TYPE: ClassVar[Type]
    REAL_TYPE: ClassVar[Type]
    INT_TYPE: ClassVar[Type]
    BOOL_TYPE: ClassVar[Type]
    STRING_TYPE: ClassVar[Type]
    ARRAY_TYPE: ClassVar[Type]
    BINARY_TYPE: ClassVar[Type]
    OBJECT_TYPE: ClassVar[Type]
    __members__: ClassVar[dict[str, Type]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

class ParseStrictness(metaclass=_pybind11_type):
    PERMISSIVE: ClassVar[ParseStrictness]
    STRICT: ClassVar[ParseStrictness]
    __members__: ClassVar[dict[str, ParseStrictness]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def is_data_uri(in_: str) -> bool: ...
def decode_data_uri(out: list[int], mime_type: str, in_: str, req_bytes: int, check_size: bool) -> tuple[bool, str]: ...
class Value(metaclass=_pybind11_type):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, b: bool) -> None: ...
    @overload
    def __init__(self, s: str) -> None: ...
    @overload
    def __init__(self, a: list[Value]) -> None: ...
    @overload
    def __init__(self, o: dict[str, Value]) -> None: ...
    @overload
    def __init__(self, i: int) -> None: ...
    @overload
    def __init__(self, v: list[int]) -> None: ...
    @overload
    def __init__(self, n: float) -> None: ...
    @overload
    def __init__(self, p: int, n: int) -> None: ...
    def is_bool(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_number(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_binary(self) -> bool: ...
    def is_array(self) -> bool: ...
    def is_object(self) -> bool: ...
    def get_number_as_double(self) -> float: ...
    def get_number_as_int(self) -> int: ...
    def array_len(self) -> int: ...
    def has(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def size(self) -> int: ...

class Parameter(metaclass=_pybind11_type):
    bool_value: bool
    has_number_value: bool
    string_value: str
    number_array: list[float]
    json_double_value: dict[str, float]
    number_value: float
    def texture_index(self) -> int: ...
    def texture_tex_coord(self) -> int: ...
    def texture_scale(self) -> float: ...
    def texture_strength(self) -> float: ...
    def factor(self) -> float: ...
    def color_factor(self) -> list[float]: ...
    def __init__(self) -> None: ...

class AnimationChannel(metaclass=_pybind11_type):
    sampler: int
    target_node: int
    target_path: str
    extras: Value
    extensions: dict[str, Value]
    target_extras: Value
    target_extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    target_extras_json_string: str
    target_extensions_json_string: str
    def __init__(self) -> None: ...

class AnimationSampler(metaclass=_pybind11_type):
    input: int
    output: int
    interpolation: str
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Animation(metaclass=_pybind11_type):
    name: str
    channels: list[AnimationChannel]
    samplers: list[AnimationSampler]
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Skin(metaclass=_pybind11_type):
    name: str
    inverse_bind_matrices: int
    skeleton: int
    joints: list[int]
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Sampler(metaclass=_pybind11_type):
    name: str
    min_filter: int
    mag_filter: int
    wrap_s: int
    wrap_t: int
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Image(metaclass=_pybind11_type):
    name: str
    width: int
    height: int
    component: int
    bits: int
    pixel_type: int
    image: list[int]
    buffer_view: int
    mime_type: str
    uri: str
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    as_is: bool
    def __init__(self) -> None: ...

class Texture(metaclass=_pybind11_type):
    name: str
    sampler: int
    source: int
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class TextureInfo(metaclass=_pybind11_type):
    index: int
    tex_coord: int
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class NormalTextureInfo(metaclass=_pybind11_type):
    index: int
    tex_coord: int
    scale: float
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class OcclusionTextureInfo(metaclass=_pybind11_type):
    index: int
    tex_coord: int
    strength: float
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class PbrMetallicRoughness(metaclass=_pybind11_type):
    base_color_factor: list[float]
    base_color_texture: TextureInfo
    metallic_factor: float
    roughness_factor: float
    metallic_roughness_texture: TextureInfo
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Material(metaclass=_pybind11_type):
    name: str
    emissive_factor: list[float]
    alpha_mode: str
    alpha_cutoff: float
    double_sided: bool
    lods: list[int]
    pbr_metallic_roughness: PbrMetallicRoughness
    normal_texture: NormalTextureInfo
    occlusion_texture: OcclusionTextureInfo
    emissive_texture: TextureInfo
    values: dict[str, Parameter]
    additional_values: dict[str, Parameter]
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class BufferView(metaclass=_pybind11_type):
    name: str
    buffer: int
    byte_offset: int
    byte_length: int
    byte_stride: int
    target: int
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    draco_decoded: bool
    def __init__(self) -> None: ...

class Accessor(metaclass=_pybind11_type):
    buffer_view: int
    name: str
    byte_offset: int
    normalized: bool
    component_type: int
    count: int
    type: int
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    min_values: list[float]
    max_values: list[float]
    sparse: AccessorSparse
    def byte_stride(self, buffer_view_object: BufferView) -> int: ...
    def __init__(self) -> None: ...

class AccessorSparse(metaclass=_pybind11_type):
    count: int
    is_sparse: bool
    indices: Any
    values: Any
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PerspectiveCamera(metaclass=_pybind11_type):
    aspect_ratio: float
    yfov: float
    zfar: float
    znear: float
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class OrthographicCamera(metaclass=_pybind11_type):
    xmag: float
    ymag: float
    zfar: float
    znear: float
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class Camera(metaclass=_pybind11_type):
    type: str
    name: str
    perspective: PerspectiveCamera
    orthographic: OrthographicCamera
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class Primitive(metaclass=_pybind11_type):
    attributes: dict[str, int]
    material: int
    indices: int
    mode: int
    targets: list[dict[str, int]]
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Mesh(metaclass=_pybind11_type):
    name: str
    primitives: list[Primitive]
    weights: list[float]
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Node(metaclass=_pybind11_type):
    def __init__(self) -> None: ...
    camera: int
    name: str
    skin: int
    mesh: int
    light: int
    emitter: int
    lods: list[int]
    children: list[int]
    rotation: list[float]
    scale: list[float]
    translation: list[float]
    matrix: list[float]
    weights: list[float]
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class Buffer(metaclass=_pybind11_type):
    name: str
    data: list[int]
    uri: str
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Asset(metaclass=_pybind11_type):
    version: str
    generator: str
    min_version: str
    copyright: str
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class Scene(metaclass=_pybind11_type):
    name: str
    nodes: list[int]
    audio_emitters: list[int]
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str
    def __init__(self) -> None: ...

class SpotLight(metaclass=_pybind11_type):
    inner_cone_angle: float
    outer_cone_angle: float
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class Light(metaclass=_pybind11_type):
    name: str
    color: list[float]
    intensity: float
    type: str
    range: float
    spot: SpotLight
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class PositionalEmitter(metaclass=_pybind11_type):
    cone_inner_angle: float
    cone_outer_angle: float
    cone_outer_gain: float
    max_distance: float
    ref_distance: float
    rolloff_factor: float
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class AudioEmitter(metaclass=_pybind11_type):
    name: str
    gain: float
    loop: bool
    playing: bool
    type: str
    distance_model: str
    positional: PositionalEmitter
    source: int
    def __init__(self) -> None: ...
    extensions: dict[str, Value]
    extras: Value
    extras_json_string: str
    extensions_json_string: str

class AudioSource(metaclass=_pybind11_type):
    name: str
    uri: str
    buffer_view: int
    mime_type: str
    def __init__(self) -> None: ...
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str

class Model(metaclass=_pybind11_type):
    def __init__(self) -> None: ...
    accessors: list[Accessor]
    animations: list[Animation]
    buffers: list[Buffer]
    buffer_views: list[BufferView]
    materials: list[Material]
    meshes: list[Mesh]
    nodes: list[Node]
    textures: list[Texture]
    images: list[Image]
    skins: list[Skin]
    samplers: list[Sampler]
    cameras: list[Camera]
    scenes: list[Scene]
    lights: list[Light]
    audio_emitters: list[AudioEmitter]
    audio_sources: list[AudioSource]
    default_scene: int
    extensions_used: list[str]
    extensions_required: list[str]
    asset: Asset
    extras: Value
    extensions: dict[str, Value]
    extras_json_string: str
    extensions_json_string: str

class SectionCheck(metaclass=_pybind11_type):
    NO_REQUIRE: ClassVar[SectionCheck]
    REQUIRE_VERSION: ClassVar[SectionCheck]
    REQUIRE_SCENE: ClassVar[SectionCheck]
    REQUIRE_SCENES: ClassVar[SectionCheck]
    REQUIRE_NODES: ClassVar[SectionCheck]
    REQUIRE_ACCESSORS: ClassVar[SectionCheck]
    REQUIRE_BUFFERS: ClassVar[SectionCheck]
    REQUIRE_BUFFER_VIEWS: ClassVar[SectionCheck]
    REQUIRE_ALL: ClassVar[SectionCheck]
    __members__: ClassVar[dict[str, SectionCheck]]
    def __init__(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __and__(self, other: object) -> int: ...
    def __rand__(self, other: object) -> int: ...
    def __or__(self, other: object) -> int: ...
    def __ror__(self, other: object) -> int: ...
    def __xor__(self, other: object) -> int: ...
    def __rxor__(self, other: object) -> int: ...
    def __invert__(self) -> int: ...

def uri_decode(in_uri: str, out_uri: str, user_data: Any) -> bool: ...
def file_exists(abs_filename: str, arg1: Any) -> bool: ...
def expand_file_path(filepath: str, userdata: Any) -> str: ...
def read_whole_file(out: list[int], err: str, filepath: str, arg3: Any) -> bool: ...
def write_whole_file(err: str, filepath: str, contents: list[int], arg3: Any) -> bool: ...
def load_image_data(image: Image, image_idx: int, err: str, warn: str, req_width: int, req_height: int, bytes: int, size: int, arg8: Any) -> bool: ...
def write_image_data(basepath: str, filename: str, image: Image, embed_images: bool, fs_cb: Any, uri_cb: Any, out_uri: str, arg7: Any) -> bool: ...
class TinyGLTF(metaclass=_pybind11_type):
    def __init__(self) -> None: ...
    def load_ascii_from_file(self, model: Model, err: str, warn: str, filename: str, check_sections: int = ...) -> bool: ...
    def load_ascii_from_string(self, model: Model, err: str, warn: str, str: str, length: int, base_dir: str, check_sections: int = ...) -> bool: ...
    def load_binary_from_file(self, model: Model, err: str, warn: str, filename: str, check_sections: int = ...) -> bool: ...
    def load_binary_from_memory(self, model: Model, err: str, warn: str, bytes: int, length: int, base_dir: str = ..., check_sections: int = ...) -> bool: ...
    def write_gltf_scene_to_file(self, model: Model, filename: str, embed_images: bool, embed_buffers: bool, pretty_print: bool, write_binary: bool) -> bool: ...
    def set_parse_strictness(self, strictness: ParseStrictness) -> None: ...
    def set_image_loader(self, load_image_data: Callable[[Image, int, str, str, int, int, int, int, Any], bool], user_data: Any) -> None: ...
    def remove_image_loader(self) -> None: ...
    def set_image_writer(self, write_image_data: Callable[[str, str, Image, bool, Any, Any, str, Any], bool], user_data: Any) -> None: ...
    def set_uri_callbacks(self, callbacks: Any, err: str = ...) -> bool: ...
    def set_fs_callbacks(self, callbacks: Any, err: str = ...) -> bool: ...
    def set_serialize_default_values(self, enabled: bool) -> None: ...
    def get_serialize_default_values(self) -> bool: ...
    def set_store_original_json_for_extras_and_extensions(self, enabled: bool) -> None: ...
    def get_store_original_json_for_extras_and_extensions(self) -> bool: ...
    def set_preserve_image_channels(self, onoff: bool) -> None: ...
    def get_preserve_image_channels(self) -> bool: ...
    def set_images_as_is(self, onoff: bool) -> None: ...
    def get_images_as_is(self) -> bool: ...
    def set_max_external_file_size(self, max_bytes: int) -> None: ...
    def get_max_external_file_size(self) -> int: ...

NULL_TYPE: Type
REAL_TYPE: Type
INT_TYPE: Type
BOOL_TYPE: Type
STRING_TYPE: Type
ARRAY_TYPE: Type
BINARY_TYPE: Type
OBJECT_TYPE: Type
PERMISSIVE: ParseStrictness
STRICT: ParseStrictness
NO_REQUIRE: SectionCheck
REQUIRE_VERSION: SectionCheck
REQUIRE_SCENE: SectionCheck
REQUIRE_SCENES: SectionCheck
REQUIRE_NODES: SectionCheck
REQUIRE_ACCESSORS: SectionCheck
REQUIRE_BUFFERS: SectionCheck
REQUIRE_BUFFER_VIEWS: SectionCheck
REQUIRE_ALL: SectionCheck
