[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trimeshv"
version = "0.1.0"
description = 'Crunge WebGPU/Trimesh Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "click ==8.1.7",
    "glfw ==2.10.2",
    "trimesh[easy] ==5.1.1",
]

[project.scripts]
trimeshv = 'trimeshv.cli:cli'

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # Crunge packages
  "../../pkg/core", "../../pkg/wgpu",
]
dependencies = ["uv", "pytest", "mypy"]
