#include <iostream>
#include <limits>

#include <pybind11/pybind11.h>
#include <pybind11/functional.h>
#include <pybind11/stl.h>

#include <cxbind/cxbind.h>
#include <crunge/yoga/crunge-yoga.h>
#include <crunge/yoga/conversions.h>

#include "../Node.h"

namespace py = pybind11;

void init_yoga_node_py_auto(py::module &_yoga, Registry &registry) {
    py::class_<Layout> Layout(_yoga, "Layout");
    registry.on(_yoga, "Layout", Layout);
        Layout
        .def_readwrite("left", &Layout::left)
        .def_readwrite("right", &Layout::right)
        .def_readwrite("top", &Layout::top)
        .def_readwrite("bottom", &Layout::bottom)
        .def_readwrite("width", &Layout::width)
        .def_readwrite("height", &Layout::height)
    ;


    py::class_<MeasureCallback> MeasureCallback(_yoga, "MeasureCallback");
    registry.on(_yoga, "MeasureCallback", MeasureCallback);
        MeasureCallback
        .def("measure", &MeasureCallback::measure
            , py::arg("width")
            , py::arg("width_mode")
            , py::arg("height")
            , py::arg("height_mode")
            , py::return_value_policy::automatic_reference)
    ;

    py::class_<DirtiedCallback> DirtiedCallback(_yoga, "DirtiedCallback");
    registry.on(_yoga, "DirtiedCallback", DirtiedCallback);
        DirtiedCallback
        .def("dirtied", &DirtiedCallback::dirtied
            , py::return_value_policy::automatic_reference)
    ;

    py::class_<Node> Node(_yoga, "Node");
    registry.on(_yoga, "Node", Node);
        Node
        .def_static("create_default", &Node::createDefault
            , py::return_value_policy::automatic_reference)
        .def_static("create_with_config", &Node::createWithConfig
            , py::arg("config")
            , py::return_value_policy::automatic_reference)
        .def_static("destroy", &Node::destroy
            , py::arg("node")
            , py::return_value_policy::automatic_reference)
        .def("reset", &Node::reset
            , py::return_value_policy::automatic_reference)
        .def("copy_style", &Node::copyStyle
            , py::arg("other")
            , py::return_value_policy::automatic_reference)
        .def("set_position_type", &Node::setPositionType
            , py::arg("position_type")
            , py::return_value_policy::automatic_reference)
        .def("set_position", &Node::setPosition
            , py::arg("edge")
            , py::arg("position")
            , py::return_value_policy::automatic_reference)
        .def("set_position_percent", &Node::setPositionPercent
            , py::arg("edge")
            , py::arg("position")
            , py::return_value_policy::automatic_reference)
        .def("set_position_auto", &Node::setPositionAuto
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("set_align_content", &Node::setAlignContent
            , py::arg("align_content")
            , py::return_value_policy::automatic_reference)
        .def("set_align_items", &Node::setAlignItems
            , py::arg("align_items")
            , py::return_value_policy::automatic_reference)
        .def("set_align_self", &Node::setAlignSelf
            , py::arg("align_self")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_direction", &Node::setFlexDirection
            , py::arg("flex_direction")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_wrap", &Node::setFlexWrap
            , py::arg("flex_wrap")
            , py::return_value_policy::automatic_reference)
        .def("set_justify_content", &Node::setJustifyContent
            , py::arg("justify_content")
            , py::return_value_policy::automatic_reference)
        .def("set_direction", &Node::setDirection
            , py::arg("direction")
            , py::return_value_policy::automatic_reference)
        .def("set_margin", &Node::setMargin
            , py::arg("edge")
            , py::arg("margin")
            , py::return_value_policy::automatic_reference)
        .def("set_margin_percent", &Node::setMarginPercent
            , py::arg("edge")
            , py::arg("margin")
            , py::return_value_policy::automatic_reference)
        .def("set_margin_auto", &Node::setMarginAuto
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("set_overflow", &Node::setOverflow
            , py::arg("overflow")
            , py::return_value_policy::automatic_reference)
        .def("set_display", &Node::setDisplay
            , py::arg("display")
            , py::return_value_policy::automatic_reference)
        .def("set_flex", &Node::setFlex
            , py::arg("flex")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis", &Node::setFlexBasis
            , py::arg("flex_basis")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis_percent", &Node::setFlexBasisPercent
            , py::arg("flex_basis")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis_auto", &Node::setFlexBasisAuto
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis_max_content", &Node::setFlexBasisMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis_fit_content", &Node::setFlexBasisFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_flex_basis_stretch", &Node::setFlexBasisStretch
            , py::return_value_policy::automatic_reference)
        .def("set_flex_grow", &Node::setFlexGrow
            , py::arg("flex_grow")
            , py::return_value_policy::automatic_reference)
        .def("set_flex_shrink", &Node::setFlexShrink
            , py::arg("flex_shrink")
            , py::return_value_policy::automatic_reference)
        .def("set_width", &Node::setWidth
            , py::arg("width")
            , py::return_value_policy::automatic_reference)
        .def("set_width_percent", &Node::setWidthPercent
            , py::arg("width")
            , py::return_value_policy::automatic_reference)
        .def("set_width_auto", &Node::setWidthAuto
            , py::return_value_policy::automatic_reference)
        .def("set_width_max_content", &Node::setWidthMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_width_fit_content", &Node::setWidthFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_width_stretch", &Node::setWidthStretch
            , py::return_value_policy::automatic_reference)
        .def("set_height", &Node::setHeight
            , py::arg("height")
            , py::return_value_policy::automatic_reference)
        .def("set_height_percent", &Node::setHeightPercent
            , py::arg("height")
            , py::return_value_policy::automatic_reference)
        .def("set_height_auto", &Node::setHeightAuto
            , py::return_value_policy::automatic_reference)
        .def("set_height_max_content", &Node::setHeightMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_height_fit_content", &Node::setHeightFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_height_stretch", &Node::setHeightStretch
            , py::return_value_policy::automatic_reference)
        .def("set_min_width", &Node::setMinWidth
            , py::arg("min_width")
            , py::return_value_policy::automatic_reference)
        .def("set_min_width_percent", &Node::setMinWidthPercent
            , py::arg("min_width")
            , py::return_value_policy::automatic_reference)
        .def("set_min_width_max_content", &Node::setMinWidthMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_min_width_fit_content", &Node::setMinWidthFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_min_width_stretch", &Node::setMinWidthStretch
            , py::return_value_policy::automatic_reference)
        .def("set_min_height", &Node::setMinHeight
            , py::arg("min_height")
            , py::return_value_policy::automatic_reference)
        .def("set_min_height_percent", &Node::setMinHeightPercent
            , py::arg("min_height")
            , py::return_value_policy::automatic_reference)
        .def("set_min_height_max_content", &Node::setMinHeightMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_min_height_fit_content", &Node::setMinHeightFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_min_height_stretch", &Node::setMinHeightStretch
            , py::return_value_policy::automatic_reference)
        .def("set_max_width", &Node::setMaxWidth
            , py::arg("max_width")
            , py::return_value_policy::automatic_reference)
        .def("set_max_width_percent", &Node::setMaxWidthPercent
            , py::arg("max_width")
            , py::return_value_policy::automatic_reference)
        .def("set_max_width_max_content", &Node::setMaxWidthMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_max_width_fit_content", &Node::setMaxWidthFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_max_width_stretch", &Node::setMaxWidthStretch
            , py::return_value_policy::automatic_reference)
        .def("set_max_height", &Node::setMaxHeight
            , py::arg("max_height")
            , py::return_value_policy::automatic_reference)
        .def("set_max_height_percent", &Node::setMaxHeightPercent
            , py::arg("max_height")
            , py::return_value_policy::automatic_reference)
        .def("set_max_height_max_content", &Node::setMaxHeightMaxContent
            , py::return_value_policy::automatic_reference)
        .def("set_max_height_fit_content", &Node::setMaxHeightFitContent
            , py::return_value_policy::automatic_reference)
        .def("set_max_height_stretch", &Node::setMaxHeightStretch
            , py::return_value_policy::automatic_reference)
        .def("set_aspect_ratio", &Node::setAspectRatio
            , py::arg("aspect_ratio")
            , py::return_value_policy::automatic_reference)
        .def("set_border", &Node::setBorder
            , py::arg("edge")
            , py::arg("border")
            , py::return_value_policy::automatic_reference)
        .def("set_padding", &Node::setPadding
            , py::arg("edge")
            , py::arg("padding")
            , py::return_value_policy::automatic_reference)
        .def("set_padding_percent", &Node::setPaddingPercent
            , py::arg("edge")
            , py::arg("padding")
            , py::return_value_policy::automatic_reference)
        .def("set_gap", &Node::setGap
            , py::arg("gutter")
            , py::arg("gap_length")
            , py::return_value_policy::automatic_reference)
        .def("set_gap_percent", &Node::setGapPercent
            , py::arg("gutter")
            , py::arg("gap_length")
            , py::return_value_policy::automatic_reference)
        .def("set_box_sizing", &Node::setBoxSizing
            , py::arg("box_sizing")
            , py::return_value_policy::automatic_reference)
        .def("get_position_type", &Node::getPositionType
            , py::return_value_policy::automatic_reference)
        .def("get_position", &Node::getPosition
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_align_content", &Node::getAlignContent
            , py::return_value_policy::automatic_reference)
        .def("get_align_items", &Node::getAlignItems
            , py::return_value_policy::automatic_reference)
        .def("get_align_self", &Node::getAlignSelf
            , py::return_value_policy::automatic_reference)
        .def("get_flex_direction", &Node::getFlexDirection
            , py::return_value_policy::automatic_reference)
        .def("get_flex_wrap", &Node::getFlexWrap
            , py::return_value_policy::automatic_reference)
        .def("get_justify_content", &Node::getJustifyContent
            , py::return_value_policy::automatic_reference)
        .def("get_direction", &Node::getDirection
            , py::return_value_policy::automatic_reference)
        .def("get_margin", &Node::getMargin
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_overflow", &Node::getOverflow
            , py::return_value_policy::automatic_reference)
        .def("get_display", &Node::getDisplay
            , py::return_value_policy::automatic_reference)
        .def("get_flex_basis", &Node::getFlexBasis
            , py::return_value_policy::automatic_reference)
        .def("get_flex_grow", &Node::getFlexGrow
            , py::return_value_policy::automatic_reference)
        .def("get_flex_shrink", &Node::getFlexShrink
            , py::return_value_policy::automatic_reference)
        .def("get_width", &Node::getWidth
            , py::return_value_policy::automatic_reference)
        .def("get_height", &Node::getHeight
            , py::return_value_policy::automatic_reference)
        .def("get_min_width", &Node::getMinWidth
            , py::return_value_policy::automatic_reference)
        .def("get_min_height", &Node::getMinHeight
            , py::return_value_policy::automatic_reference)
        .def("get_max_width", &Node::getMaxWidth
            , py::return_value_policy::automatic_reference)
        .def("get_max_height", &Node::getMaxHeight
            , py::return_value_policy::automatic_reference)
        .def("get_aspect_ratio", &Node::getAspectRatio
            , py::return_value_policy::automatic_reference)
        .def("get_border", &Node::getBorder
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_padding", &Node::getPadding
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_gap", &Node::getGap
            , py::arg("gutter")
            , py::return_value_policy::automatic_reference)
        .def("get_box_sizing", &Node::getBoxSizing
            , py::return_value_policy::automatic_reference)
        .def("insert_child", &Node::insertChild
            , py::arg("child")
            , py::arg("index")
            , py::return_value_policy::automatic_reference)
        .def("remove_child", &Node::removeChild
            , py::arg("child")
            , py::return_value_policy::automatic_reference)
        .def("get_child_count", &Node::getChildCount
            , py::return_value_policy::automatic_reference)
        .def("get_parent", &Node::getParent
            , py::return_value_policy::automatic_reference)
        .def("get_child", &Node::getChild
            , py::arg("index")
            , py::return_value_policy::automatic_reference)
        .def("set_measure_func", &Node::setMeasureFunc
            , py::arg("measure_func")
            , py::return_value_policy::automatic_reference)
        .def("unset_measure_func", &Node::unsetMeasureFunc
            , py::return_value_policy::automatic_reference)
        .def("call_measure_func", &Node::callMeasureFunc
            , py::arg("width")
            , py::arg("width_mode")
            , py::arg("height")
            , py::arg("height_mode")
            , py::return_value_policy::automatic_reference)
        .def("set_dirtied_func", &Node::setDirtiedFunc
            , py::arg("dirtied_func")
            , py::return_value_policy::automatic_reference)
        .def("unset_dirtied_func", &Node::unsetDirtiedFunc
            , py::return_value_policy::automatic_reference)
        .def("call_dirtied_func", &Node::callDirtiedFunc
            , py::return_value_policy::automatic_reference)
        .def("mark_dirty", &Node::markDirty
            , py::return_value_policy::automatic_reference)
        .def("is_dirty", &Node::isDirty
            , py::return_value_policy::automatic_reference)
        .def("mark_layout_seen", &Node::markLayoutSeen
            , py::return_value_policy::automatic_reference)
        .def("has_new_layout", &Node::hasNewLayout
            , py::return_value_policy::automatic_reference)
        .def("calculate_layout", &Node::calculateLayout
            , py::arg("width")
            , py::arg("height")
            , py::arg("direction")
            , py::return_value_policy::automatic_reference)
        .def("get_computed_left", &Node::getComputedLeft
            , py::return_value_policy::automatic_reference)
        .def("get_computed_right", &Node::getComputedRight
            , py::return_value_policy::automatic_reference)
        .def("get_computed_top", &Node::getComputedTop
            , py::return_value_policy::automatic_reference)
        .def("get_computed_bottom", &Node::getComputedBottom
            , py::return_value_policy::automatic_reference)
        .def("get_computed_width", &Node::getComputedWidth
            , py::return_value_policy::automatic_reference)
        .def("get_computed_height", &Node::getComputedHeight
            , py::return_value_policy::automatic_reference)
        .def("get_computed_layout", &Node::getComputedLayout
            , py::return_value_policy::automatic_reference)
        .def("get_computed_margin", &Node::getComputedMargin
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_computed_border", &Node::getComputedBorder
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("get_computed_padding", &Node::getComputedPadding
            , py::arg("edge")
            , py::return_value_policy::automatic_reference)
        .def("set_is_reference_baseline", &Node::setIsReferenceBaseline
            , py::arg("is_reference_baseline")
            , py::return_value_policy::automatic_reference)
        .def("is_reference_baseline", &Node::isReferenceBaseline
            , py::return_value_policy::automatic_reference)
        .def("set_always_forms_containing_block", &Node::setAlwaysFormsContainingBlock
            , py::arg("always_form_containing_block")
            , py::return_value_policy::automatic_reference)
    ;


}