[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yogademo"
version = "0.1.0"
description = 'Crunge Yoga Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "glfw ==2.10.2",
    "loguru",
    "PyGLM",
    "imageio",
]
[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # Crunge packages
  "../../pkg/core", "../../pkg/imgui", "../../pkg/wgpu", "../../pkg/skia", "../../pkg/yoga",
  "../../pkg/sdl",
]
dependencies = ["uv", "pytest", "mypy"]
