[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "impyodemo"
version = "0.1.0"
description = 'Crunge ImPyo Demo'
requires-python = ">=3.8"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "pyo ~= 1.0.5",
    "mido ~=1.3.2",
]

[tool.hatch.envs.default]
python = "3.10"

