import glm

#RESERVED_BINDINGS = 3
#TEXTURE_BINDING_START = RESERVED_BINDINGS

RESERVED_LOCATIONS = 1
LOCATION_START = RESERVED_LOCATIONS + 1

WORLD_AXIS_X = glm.vec3(1.0, 0.0, 0.0)
WORLD_AXIS_Y = glm.vec3(0.0, 1.0, 0.0)
WORLD_AXIS_Z = glm.vec3(0.0, 0.0, 1.0)
WORLD_SCALE = 1

SAMPLE_COUNT = 4
#SAMPLE_COUNT = 1