[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wrender"
version = "0.1.0"
description = 'Crunge WebGPU/GLTF Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "loguru",
    "click",
    "PyGLM",

    "Jinja2",
]

[project.scripts]
wrender = 'wrender.cli:cli'

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # Crunge packages
  "../../pkg/core", "../../pkg/imgui", "../../pkg/wgpu", "../../pkg/skia", "../../pkg/yoga",
  "../../pkg/sdl", "../../pkg/gltf",
  "../../pkg/engine", "../../pkg/demo",
]
dependencies = ["uv", "pytest", "mypy"]
