[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wgpudemo"
version = "0.1.0"
description = 'Crunge WebGPU Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "glfw ==2.10.2",
    "trimesh[easy] ==5.1.1",
    "loguru",
    "PyGLM",
    "imageio",
    "imgui-bundle",
]

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # KCore
  "../../../kcore",

  # Crunge packages
  "../../pkg/core", "../../pkg/wgpu",
]
dependencies = ["uv", "pytest", "mypy"]
