[tool.poetry]
name = "wgpudemo"
version = "0.1.0"
description = ""
authors = ["Kurtis Fields <kurtisfields@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11.0"
#crunge-core = {path = "../core",  develop = true}
#crunge-wgpu = {path = "../wgpu",  develop = true}
#crunge-imgui = {path = "../imgui",  develop = true}
glfw = "^2.6.4"
loguru = "^0.7.2"
PyGLM = "^2.7.1"
trimesh = "^4.0.5"
imageio = "^2.33.1"
gltflib = "^1.0.13"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
