[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "imflo"
version = "0.1.0"
description = 'ImFlo'
requires-python = ">=3.8"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "Rx ~=3.2.0",
    "scipy ~= 1.12.0"
]
