source = '../../lib/dawn/inc/webgpu/webgpu_cpp.h'
target = 'src/crunge/wgpu/bindings/generated.cpp'

module = '_wgpu'

flags = [
    '-x', 'c++',
    '-std=c++17',
    '-I../../lib/dawn/inc',
]

excludes = [
    # Wrapped
    # Internal / Ignored
    'dawn::IsDawnBitmask', # TODO: Should skip templates in the transpiler
    # These three have a weird signature:  const char* const * 
    'wgpu::DawnInstanceDescriptor::additionalRuntimeSearchPaths',
    'wgpu::DawnTogglesDeviceDescriptor::forceEnabledToggles',
    'wgpu::DawnTogglesDeviceDescriptor::forceDisabledToggles'
    #Obsolete
]

overloaded = [
]
