[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "enginedemo"
version = "0.1.0"
description = 'Crunge Engine Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
    "trimesh ==5.0.0",
    "freetype-py ==2.5.1",
    "uharfbuzz ==0.47.0"
]

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # Crunge packages
  "../../pkg/core", "../../pkg/imgui", "../../pkg/wgpu", "../../pkg/skia", "../../pkg/yoga",
  "../../pkg/sdl",
  "../../pkg/engine", "../../pkg/gltf"
]
dependencies = ["uv", "pytest", "mypy"]
