[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["box2d_demo"]

[project]
name = "box2d-demo"
version = "0.1.0"
description = 'Crunge Box2D Demo'
requires-python = ">=3.12"
authors = [{ name = "Kurtis Fields", email = "kurtisfields@gmail.com" }]

dependencies = [
  "scipy"
]

[tool.hatch.envs.default]
python = "3.12"
installer = "uv"
workspace.members = [
  # Build toolchain
  "../../../cxbuild",
  # Generation toolchain (cxbuild requirement)
  "../../../cxbind",

  # Crunge packages
  "../../pkg/core", "../../pkg/imgui", "../../pkg/wgpu", "../../pkg/skia", "../../pkg/yoga",
  "../../pkg/sdl", "../../pkg/box2d", "../../pkg/tmx",
  "../../pkg/engine", "../../pkg/demo",
]
dependencies = ["uv", "pytest", "mypy"]
